exoscale/cli

.golangci.yml
Jenkinsfile

We can perform `gofmt` compliance using the `gofmt` linter of golangci-linter.

Perform gofmt testing with golangci-linter

---

cmd/config.go
cmd/root.go
cmd/sshkey_list.go
cmd/vm_create.go

Example
you can choose a default sshkey pair
```
[[accounts]]
account = "exoscale-1"
computeEndpoint = "https://api.exoscale.ch/compute"
defaultSSHKey = ""
defaultTemplate = "Linux Ubuntu 18.04 LTS 64-bit"
defaultZone = "ch-gva-2"
key = "XXXXXXX"
name = "account-test"
secret = "XXXXX"
```
or you can leave it blank if you don't want default sshkey pair.
https://github.com/exoscale/cli/issues/15
It's used when you want to deploy a virtual machine if you have a default sshkey pair exo will use this key

Add default sshkey pair

---

cmd/api_layout.go

delete and update were missing.
```console
% exo api vm-group                                                                                                          
VM group management                                                                                                                          
Usage:                                                                                                                                       
exo api vm-group [command]                                                                                                                 
Aliases:  
vm-group, vg
Available Commands:
create      Creates a vm group
delete      Deletes a vm group …
```

api: add missing vm-group calls

---

go.mod
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/README.md
vendor/github.com/exoscale/egoscale/nics.go
vendor/github.com/exoscale/egoscale/version.go
vendor/github.com/exoscale/egoscale/virtual_machines.go
vendor/modules.txt

https://github.com/exoscale/egoscale/pull/352
bumping egoscale to v0.12.2 fixes that.

vm: show breaks on non-UUID content

---

cmd/root.go

issue #21 
-A, --account flag is overwritten in some exo api cmd.
help wanted to find another solution

Account flag overwritten in exo api

---

cmd/privnet.go
cmd/privnet_associate.go
cmd/privnet_show.go
cmd/vm_update_ip.go
cmd/vm_update_nic_ip.go

This call allows to modify the static ip associated to a nic.
```
$ ./exo vm updatenicip 2269764c-39ef-43a4-9a97-dc17a155bb2e 10.0.0.5
Updating the nic "2269764c-39ef-43a4-9a97-dc17a155bb2e" . success.
Instance ID:           8f0d4701-dce1-432c-87bd-5548c0860a43
Isntance Hostname:     test-vm
Instance Display name: test-vm
┼──────────────────────────────────────┼──────────────────────────────────────┼────────────┼
│                NIC ID                │              NETWORK ID              │ IP ADDRESS │
┼──────────────────────────────────────┼──────────────────────────────────────┼────────────┼
│ 2269764c-39ef-43a4-9a97-dc17a155bb2e │ 932e1e8e-9a07-4449-8894-b0ad52fcec6d │ 10.0.0.5   │
┼──────────────────────────────────────┼──────────────────────────────────────┼────────────┼
```

Add the Cloudstack updateVmNicIp call

---

.goreleaser.yml
cmd/root.go

Fixes #55
```console
% docker run --rm -it ubuntu:cosmic sh
Selecting previously unselected package exoscale-cli.
(Reading database ... 4032 files and directories currently installed.)
Preparing to unpack .../exoscale-cli_..._linux_amd64.deb ...
Unpacking exoscale-cli (1.0.3) ...
Setting up exoscale-cli (1.0.3) ...
exo ... 0d80d1e61b241bef498af5f1f1f908560d5f0c1d (egoscale 0.12.2)
```
**NB** it will also change its name for our macOS users.

goreleaser: change project name to exoscale-cli

---

cmd/config.go
cmd/config_show.go
cmd/root.go
cmd/sos.go

Fixes #18 
```toml
[[accounts]]
key = "EXOc94bc655ff901b7218a5c3cd"
secretCommand = ["secret-tool", "lookup", "Exoscale", "EXOc94bc655ff901b7218a5c3cd"]
```
```console
% exo config show
Default template: Linux Ubuntu 18.04 LTS 64-bit
Name:         yoan.blanc@exoscale.ch
API Key:      EXOc94bc655ff901b7218a5c3cd
API Secret:   secret-tool lookup Exoscale EXOc94bc655ff901b7218a5c3cd
Account:      yoan.blanc@exoscale.ch
Default zone: ch-gva-2
% exo zone list
```
|   NAME   |                  ID                  |
|----------|--------------------------------------|
| ch-gva-2 | 1747ef5e-5451-41fd-9f1a-58913bae9702 |
| ch-dk-2  | 381d0a95-ed4a-4ad9-b41c-b97073c1a433 |
| at-vie-1 | b0fcd72f-47ad-4779-a64f-fe4de007ec72 |
| de-fra-1 | de88c980-78f6-467c-a431-71bcc88e437f |

config: allow secret to come from an external command

---

cmd/root.go

Configurations currently live in `~/.exoscale` this patchs switches the default location to `$XDG_CONFIG_HOME/exoscale` but keeps looking in the previous location to avoid breaking existing setups.

config: use $XDG_CONFIG_HOME

---

cmd/config.go
cmd/config_show.go
cmd/root.go
cmd/sos.go

This restores the functionality.
As an added bonus, this also restores `exo config` functionality, which also got broken in #57 (marshaling of configs failed both ways)

PR #57 broke credential reading from configuration

---

cmd/config.go
cmd/root.go

:warning: master truncates the `~/.exoscale/exoscale.toml` file :warning:
**now**
```console
% truncate -s 0 ~/.exoscale/exoscale.toml
% exo config
default account not defined
```
**then**
```console
% truncate -s 0 ~/.exoscale/exoscale.toml
% exo config                 
We've found a "cloudstack.ini" configuration file with the following configurations:
...
```

config: unpanic when exoscale.toml is empty

---

cmd/config_list.go
cmd/config_show.go
cmd/root.go

#62 moves the default config folder, let's make it visible.
```console
% exo config show
ppyoan
Account:          yoan.blanc@exoscale.ch
API Key:          EXOc94bc655ff901b7218a5c3cd
API Secret:       secret-tool lookup Exoscale EXOc94bc655ff901b7218a5c3cd
Default zone:     ch-gva-2
Default template: Linux Ubuntu 18.04 LTS 64-bit
Endpoint:         https://api.exoscale.ch/compute
DNS Endpoint:     https://api.exoscale.ch/dns
Configuration:    /home/u/.exoscale/exoscale.toml
Storage:          /home/u/.exoscale
```

config: store data next to config

---

cmd/api.go

go run main.go api zone list keyword=bar tags=tag
```
Raw arg(s) not allowed "keyword=bar, tags=tag"
Usage:
exo api zone list [flags]
Aliases:
list, ls, listZones
Flags:
--available        true if you want to retrieve all available Zones. False if you only want to return the Zones from which you have at least one VM. Default is false. (default nil)
--id UUID          the ID of the zone (default nil)
--keyword string   List by keyword
--name string      the name of the zone
--page int
--pagesize int
--showcapacities   flag to display the capacity of the zones (default nil)
--tags tag         List zones by resource tags (key/value pairs)
-h, --help             help for list
Global Flags:
-C, --config string        Specify an alternate config file [env EXOSCALE_CONFIG]
-d, --debug …
```

Fix (#68) Api raw args not allowed

---

cmd/sos.go

SOS with `EXOSCAL_TRACE=`:
```
---------START-HTTP---------
GET /bucket-example/?location= HTTP/1.1
Host: sos-ch-dk-2.exo.io
User-Agent: Minio (darwin; amd64) minio-go/v6.0.6
Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXXX/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20181130T141747Z
Accept-Encoding: gzip
HTTP/2.0 200 OK
Content-Length: 134
Content-Type: application/xml
Date: Fri, 30 Nov 2018 14:17:53 GMT
Server: nginx
X-Amz-Bucket-Region: ch-dk-2
X-Amz-Id-2: eeaab1bd-1932-4d4e-bdbd-b1e72d04bae9
X-Amz-Request-Id: eeaab1bd-1932-4d4e-bdbd-b1e72d04bae9
X-Amzn-Requestid: eeaab1bd-1932-4d4e-bdbd-b1e72d04bae9
---------END-HTTP---------
```

Add EXOSCALE_TRACE= on SOS

---

CHANGELOG.md
cmd/firewall_add.go
cmd/firewall_remove.go

* if protocol is not set, rule will be created with
* protocol set to all
* port set to 0
```console
% exo firewall add egress --cidr 1.2.3.4/32 --port 45678
SOURCE                   │ PROTOCOL │   PORT   │ 
CIDR 1.2.3.4/32          │ all      │ 0        │             │ 
```
Maybe we should not accept --port without  --protocol 
* if protocol is set to all with --port
It is strange to have the possibility to set protocol to all with the cli but not through the portal
*exo 1.0.6 e886eca13deef7a2016a9c542fb3eca79deab4a4 (egoscale 0.13.2)*

firewall: fix --my-ip and flagless add

---

cmd/sshkey_delete.go

Delete all sshkey in a single command

exo sshkey delete --all

---

cmd/affinitygroup.go
cmd/affinitygroup_show.go
cmd/vm_show.go
go.mod
vendor/github.com/exoscale/egoscale/.travis.yml
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/affinity_groups.go
vendor/github.com/exoscale/egoscale/version.go
vendor/github.com/exoscale/egoscale/virtual_machines.go
vendor/modules.txt

Output example:
```console
$ exo affinitygroup show aa0
┼───────────────────────┼──────────────────────────────────────┼
│ INSTANCE DISPLAY NAME │             INSTANCE ID              │
┼───────────────────────┼──────────────────────────────────────┼
│ vm1                   │ xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx │
│ vm2                   │ yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy │
┼───────────────────────┼──────────────────────────────────────┼
$ exo vm show vm1
┼───────────────────────┼──────────────────────────────────────┼
│          VM1          │                                      │
┼───────────────────────┼──────────────────────────────────────┼
│ State                 │ Running                              │
│ OS Template           │ Linux Ubuntu 18.04 LTS 64-bit        │
│ Region …
```

CLI: show VMs in anti-affinity group

---

cmd/config.go
cmd/config_delete.go
cmd/config_set.go
cmd/config_show.go
cmd/root.go

`exo config` should play nicer now.
**env**
```
% exo config     
remove ENV credentials variables to use config
% exo config show
environment variables
Account:          unknown
API Key:          EXO4d60e5e69f0225b35cb4fa05
API Secret:       ××××××××××
Default zone:     ch-dk-2
Default template: Linux Ubuntu 18.04 LTS 64-bit
Configuration:    environment variables
```
**no env**
```
% exo config
We've found a "cloudstack.ini" configuration file with the following configurations:
...
% exo config show
no accounts are defined
```

config: improve life of people without config

---

cmd/root.go

be resilient when the config doesn't have any zone set.

config: panic on empty defaultZone

---

cmd/vm_firewall.go

Fixes #113.
Example usage:
```console
$ ./exo vm show vm1
┼───────────────────────┼──────────────────────────────────────┼
│          VM1          │                                      │
┼───────────────────────┼──────────────────────────────────────┼
│ State                 │ Stopped                              │
│ OS Template           │ Linux Ubuntu 18.04 LTS 64-bit        │
│ Region                │ ch-dk-2                              │
│ Instance Type         │ Tiny                                 │
│ Disk                  │ 10 GB                                │
│ Instance Hostname     │ vm1                                  │
│ Instance Display Name │ vm1                                  │
│ Instance Username     │ ubuntu                               │
│ Created on            │ …
```

Allow VM instance security group modification

---

cmd/kube_create.go

Fix #122 
```console
% exo labe kube list
|   NAME   |  IP ADDRESS   |  SIZE  | VERSION |  STATE  |
|----------|---------------|--------|---------|---------|
| min1kube | 185.19.29.246 | Medium | 1.14.0  | Running |
% kubectl cluster-info
Kubernetes master is running at https://185.19.29.246:6443
KubeDNS is running at https://185.19.29.246:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
% kubectl get nodes        
NAME       STATUS   ROLES    AGE   VERSION
min1kube   Ready    master   76s   v1.14.0
```

kube: force to accept the new conf of cloud-init

---

cmd/vm_reset.go

Be more like the web UI.
ping @jessicatoscani 
```console
% exo vm reset nom --template="Linux Ubuntu 18.10"
[+] sure you want to reset "nom" virtual machine [yN]: y
Resetting "nom" using "Linux Ubuntu 18.10 64-bit 10G Disk (2018-10-18-74807a)". success.
% exo vm reset nom --template="Linux Ubuntu 18.04"
[+] sure you want to reset "nom" virtual machine [yN]: y
Resetting "nom" using "Linux Ubuntu 18.04 LTS 64-bit 10G Disk (2018-10-03-855a85)". success.
% exo vm reset nom --template="Linux Ubuntu 18.10"
[+] sure you want to reset "nom" virtual machine [yN]: y
Resetting "nom" using "Linux Ubuntu 18.10 64-bit 10G Disk (2018-10-18-74807a)". success.
```

vm: reset could accept a template parameter

---

cmd/kube.go
cmd/kube_create.go
cmd/kube_list.go

more flags and calico 3.6 support.
```console
% exo lab kube create min1kube --debug --calico-version 3.4 --docker-version 18.06 --version 1.12.7
% exo lab kube list  
|   NAME   |   IP ADDRESS    |  SIZE  | VERSION | CALICO | DOCKER |  STATE  |
|----------|-----------------|--------|---------|--------|--------|---------|
| min1kube | 159.100.251.200 | Medium | 1.12.7  | 3.4    | 18.06  | Running |
```

kube: calico/docker version

---

cmd/eip_create.go
cmd/eip_show.go
go.mod
vendor/github.com/exoscale/egoscale/.gitignore
vendor/github.com/exoscale/egoscale/README.md
vendor/github.com/exoscale/egoscale/addresses.go
vendor/github.com/exoscale/egoscale/dns.go
vendor/github.com/exoscale/egoscale/version.go
vendor/modules.txt

- in eip_create.go, add new parameters for the healthcheck definition
- in eip_show.go, show the healthcheck parameters.
```
./exo -A dev eip create --mode http --path "/" --port 8080
┼──────────┼─────────────────┼──────────────────────────────────────┼
│   ZONE   │       IP        │                  ID                  │
┼──────────┼─────────────────┼──────────────────────────────────────┼
│ ch-gva-2 │ 159.100.241.213 │ f0b14bcc-cd82-4364-b36d-b63d2e05af8d │
┼──────────┼─────────────────┼──────────────────────────────────────┼
./exo -A dev eip show f0b14bcc-cd82-4364-b36d-b63d2e05af8d
┼──────────┼─────────────────┼─────────────────┼────────────────────┼──────────┼──────┼──────┼──────┼──────────────┼────────────┼─────────┼
│   ZONE   │       IP        │ VIRTUAL MACHINE │ VIRTUAL MACHINE …
```

eip_create/eip-show: support for healthchecks

---

cmd/template.go
cmd/template_list.go

Users should be able to list community, self, and featured templates.
By default, featured template are shown.
```
./exo vm template list
┼──────────────────────────────────┼──────┼───────────────────┼──────────────────────────────────────┼──────────┼
│         OPERATING SYSTEM         │ DISK │   RELEASE DATE    │                  ID                  │ CATEGORY │
┼──────────────────────────────────┼──────┼───────────────────┼──────────────────────────────────────┼──────────┼
│ CiscoASAv-9101_001               │ 8    │ 2019-04-10        │ bbec29ac-6f78-4a4e-81a4-eb5d5d6983a1 │ featured │
│ FreeBSD pfSense 2.5 64-bit       │ 1    │ 2019-04-16        │ 628f4609-8bf1-43df-b2fe-db315acdf9b0 │ featured │
│ Linux CentOS 7.6 64-bit          │ 1    │ 2019-03-11        │ …
```

template list: add the templateFilter parameter

---

cmd/sos_upload.go

Fix content-type sniffing on files < 512 bytes

---

CHANGELOG.md
cmd/client.go
cmd/config.go
cmd/root.go

This change adds support for user-defined arbitrary headers to be
injected to every outgoing HTTP request to the Exoscale API.
Configuration is done through a new `customHeaders` account key in the
`exoscale.toml` file:
```toml
[[accounts]]
account = "myaccount"
defaultTemplate = "Linux Ubuntu 18.04 LTS 64-bit"
defaultZone = "ch-gva-2"
endpoint = "https://api.exoscale.ch/compute"
key = "EXO************************"
name = "myaccount"
secret = "*******************************************"
[[accounts.customHeaders]]
X-Custom-Header1 = "foo"
X-Custom-Header2 = "bar"
```
Story: [Support arbitrary headers in egoscale and cli](https://app.clubhouse.io/exoscale/story/2543)

client: add support for custom HTTP headers

---

cmd/template.go

We now have custom templates, so the name of a template can be
whatever the user wants. We should not ignore templates because they
does not match the regex.
fix https://github.com/exoscale/cli/issues/140

template: don't filter templates.

---

.goreleaser.yml
Makefile

This change aligns the binaries generated using [GoReleaser](https://goreleaser.com/) and the standard Makefile by setting the same version/commit information at build time.
Before this change, building the binary using the Makefile would produce a `exo version` output such as `exo dev n/a (egoscale 0.17.0)`.
Now, if building from source on a tag the output would be: `exo v1.2.0 0d64517fd734f675ec2b225d002a9a2f9857594e (egoscale 0.17.0)`
If building from master, it will be: `exo dev c251678065838b95a1eff2cdf7e3b78b9469b03d (egoscale 0.17.1)`

Set build version/commit in Makefile

---

CHANGELOG.md
cmd/affinitygroup_show.go
cmd/config.go
cmd/config_delete.go
cmd/config_set.go
cmd/config_show.go
cmd/privnet_show.go
cmd/runstatus_incident_show.go
cmd/runstatus_maintenance_show.go
cmd/runstatus_service_show.go
cmd/runstatus_show.go
cmd/status.go
cmd/template_show.go
cmd/vm_show.go
table/table.go

This change normalizes the `exo * show` commands output on a table-based format:
```console
$ exo config show
#
#
marc
Account:          marc
API Key:          EXO000000000000000000000000
API Secret:       ××××××××××
Default zone:     ch-gva-2
Default template: Linux Ubuntu 18.04 LTS 64-bit
Configuration:    /Users/marc/.exoscale/exoscale.toml
Storage:          /Users/marc/.exoscale
#
#
┼──────────────────────┼─────────────────────────────────────┼
│         MARC         │                                     │
┼──────────────────────┼─────────────────────────────────────┼
│ Account Name         │ marc                                │
│ API Key              │ EXO000000000000000000000000         │
│ API Secret           │ ×××××××××××××××××××××××××××         │
│ Default Zone         │ …
```

CLI: normalize output format across `exo * show` commands

---

cmd/kube_create.go
cmd/template.go
cmd/template_show.go
cmd/vm_create.go
cmd/vm_reset.go
cmd/zone.go
go.mod

- Add the template-filter option
- Add a validateTemplateFilter function to validate the
--template-filter parameter
- Rewrite getTemplateByName to support template-filter
- Add the template-filter option
- Add a zone option (useful for custom templates)
- Add the template-filter option
- Add the template-filter option

Support template-filter in various commands

---

CHANGELOG.md
cmd/template_list.go
cmd/template_show.go

This change adds the template zone to displayed information:
```console
$ ./exo vm template list --mine
┼──────────────────┼──────┼──────────────┼──────────────────────────────────────┼──────────┼──────────┼
│ OPERATING SYSTEM │ DISK │ RELEASE DATE │                  ID                  │   ZONE   │ CATEGORY │
┼──────────────────┼──────┼──────────────┼──────────────────────────────────────┼──────────┼──────────┼
│ mybuntu          │ 10   │ 2019-05-03   │ e08ca8e4-c778-4ec8-b163-16471dca895a │ ch-gva-2 │ self     │
┼──────────────────┼──────┼──────────────┼──────────────────────────────────────┼──────────┼──────────┼
$ ./exo vm template show e08ca8e4-c778-4ec8-b163-16471dca895a
┼───────────┼──────────────────────────────────────┼
│  MYBUNTU  │                                      │ …
```

template: display zone in list/show commands

---

CHANGELOG.md
cmd/vm_reboot.go
cmd/vm_stop.go

This change adds a confirmation request on a `vm stop/reboot`
commands, as for the `delete` and `reset` commands.

vm: require confirmation on stop/reboot

---

cmd/version.go

Looks like this is not used anymore... `¯\_(ツ)_/¯`

Remove unused cmd/version.go file

---

CHANGELOG.md
cmd/sos_upload.go

This change disables SOS upload transfer logging activity, which now can
be enabled by passing the `--log|-l` flag.

sos: don't log upload activity by default

---

cmd/template_list.go

This change fixes a bug in the `vm template list` command where a user could not see private templates registered in a different zone that the default zone of the current account: the new `--zone` allows the user to specify the zone to list the templates from.

vm template: fix bug in "list" command

---

cmd/zone.go

This only affects the help text - "exo zones" listed de-muc-1 already.

Add de-muc-1 to zones list. Servus!

---

CHANGELOG.md
cmd/firewall_add.go

This change requires a CIDR or a Security Group to be specified when
adding a rule.

firewall: check for CIDR or SG when adding a rule

---

CHANGELOG.md
cmd/sos_list.go

This change prevents the `sos list` command from panicking if SOS
returns bogus entries.

sos: fix `list` command panic

---

CHANGELOG.md
cmd/kube_create.go

This change fixes a race condition happening in the node instance upgrade stage of the `lab kube create` command, where the command would try to run `apt` related commands while a `unattended-upgrades` process was already running: we now wait until the lock on the `/var/lib/dpkg/lock-frontend` is removed before starting the upgrade procedure.
Fixes #166

lab kube: fix node instance upgrade stage

---

CHANGELOG.md
cmd/affinitygroup_delete.go

This change fixes a bug in the `affinitygroup delete` command, where user confirmation prompt reply would not have no effect and items would be deleted anyway.

affinitygroup: fix delete confirmation prompt bug

---

cmd/privnet_delete.go

The `forced` parameter should not be passed to the `deleteNetwork`
call.
```
$ exo privnet create aaaa
┼──────┼─────────────┼──────────────────────────────────────┼──────┼
│ NAME │ DESCRIPTION │                  ID                  │ DHCP │
┼──────┼─────────────┼──────────────────────────────────────┼──────┼
│ aaaa │             │ ec8c555b-cc3f-4639-8696-4a2f95970b0c │ n/a  │
┼──────┼─────────────┼──────────────────────────────────────┼──────┼
$ ./exo privnet delete --force aaaa
delete "ec8c555b-cc3f-4639-8696-4a2f95970b0c" privnet ⠙                         done!
$ exo privnet create aaaa
┼──────┼─────────────┼──────────────────────────────────────┼──────┼
│ NAME │ DESCRIPTION │                  ID                  │ DHCP │
┼──────┼─────────────┼──────────────────────────────────────┼───── …
```

privnet delete: do not set the forced parameter

---

CHANGELOG.md
cmd/vm_create.go

This change checks for maximum allowed user-data length before sending
the instance creation request:
```console
$ base64 -w0 userdata.txt | wc -c
32768
$ ./exo vm create test --cloud-init-file=userdata.txt
error: user-data maximum allowed length is 32768 bytes
```

vm: create: check for maximum user-data length

---

CHANGELOG.md
cmd/affinitygroup_create.go
cmd/dns_create.go
cmd/dns_delete.go
cmd/dns_records_add.go
cmd/dns_records_update.go
cmd/dns_remove.go
cmd/eip_create.go
cmd/eip_update.go
cmd/firewall_create.go
cmd/kube_create.go
cmd/kube_delete.go
cmd/privnet_associate.go
cmd/privnet_update.go
cmd/request.go
cmd/root.go
cmd/runstatus_create.go
cmd/runstatus_delete.go
cmd/runstatus_incident_remove.go
cmd/runstatus_maintenance_remove.go
cmd/runstatus_service_create.go
cmd/runstatus_service_delete.go
cmd/sshkey_create.go
cmd/sshkey_upload.go
cmd/template_register.go
cmd/vm_create.go
cmd/vm_firewall.go
cmd/vm_reset.go
cmd/zone.go

This change introduces a "quiet" mode (global flag `--quiet`|`-Q`, which
when specified disabled non-essential command outputs and can be better
suited for running bulk `exo` commands in shell scripts.

cmd: add quiet mode global flag

---

CHANGELOG.md
cmd/sos_upload.go

This change fixes a bug where the CLI progress bar would hang after
uploading an empty file. The fix is actually a workaround as the problem
is located in upstream minio-go library:
https://github.com/vbauerster/mpb/issues/7#issuecomment-518756758
https://github.com/minio/minio-go/issues/1146
Fixes #138.

sos: fix empty files upload hanging bug

---

CHANGELOG.md
cmd/sos_delete.go

This change introduces a new `--recursive` option flag to the `sos delete` command, allowing to empty the targeted bucket before deleting it.
Fixes #164.

sos: delete: add "--recursive" flag

---

CHANGELOG.md
cmd/privnet.go
cmd/privnet_associate.go
cmd/privnet_delete.go
cmd/privnet_dissociate.go
cmd/privnet_show.go
cmd/privnet_update.go
cmd/vm_create.go
cmd/vm_update_ip.go

This change improves the Private Network retrieval by name, following a
bug report demonstrating that some CLI operations fail in presence of
multiple similarly prefixed Private Networks since the Exoscale API
doesn't support Network resource search by name.
Before the change:
```console
$ exo privnet list
┼──────────────────────────────────────┼─────────┼──────────┼──────┼───────────┼
│                  ID                  │  NAME   │   ZONE   │ DHCP │ INSTANCES │
┼──────────────────────────────────────┼─────────┼──────────┼──────┼───────────┼
│ 9a67b55f-fe2a-4aab-b988-fcd3e654dbdd │ test100 │ ch-gva-2 │ n/a  │ 0         │
│ 5c80218f-9887-4f02-afc6-fd8d300b837e │ test10  │ ch-gva-2 │ n/a  │ 0         │
│ bcb9d7e3-a997-48ee-bc15-5f45c5a003a3 │ test1   │ ch-gva-2 │ n/a  │ 0         │ …
```

network: fix network retrieval by name

---

cmd/serviceoffering.go

Some Exoscale calls needs the service offering ID.
This commit adds the ID in the `exo vm serviceoffering` output:
```
./exo vm serviceoffering
┼──────────────────────────────────────┼─────────────────────┼──────────────┼────────┼
│                  ID                  │        NAME         │     CPU      │  RAM   │
┼──────────────────────────────────────┼─────────────────────┼──────────────┼────────┼
│ 7c12e6df-6096-43e6-b9e4-3cb7b4e3f4c8 │ Micro               │ 1× 2198 MHz  │ 512 MB │
│ 84925525-7825-418b-845b-1aed179bbc40 │ Tiny                │ 1× 2198 MHz  │ 1 GB   │
│ f5c533d9-d8db-45b4-89c8-04eed02662ba │ Small               │ 2× 2198 MHz  │ 2 GB   │
│ 5e5fb3c6-e076-429d-9b6c-b71f7b27760b │ Medium              │ 2× 2198 MHz  │ 4 GB   │
│ f875f4dd-dbd4-48ad-a151-a7ba9d303008 │ Large …
```

listServiceOffering: show the ID

---

CHANGELOG.md
cmd/zone.go

This change fixes the `exo zone` command to honor user custom output
formatting options.
Fixes #176.

zone: honor command output formatting options

---

CHANGELOG.md
cmd/serviceoffering.go

This change fixes the `exo vm serviceoffering` command to honor user
custom output formatting options.

vm: serviceoffering: honor command output formatting options

---

cmd/sos_create.go

Specifying an invalid Exoscale zone to `exo sos create` can result in a
long silent hang before the HTTP retry policy finally gives up and
returns an error. This changes first check that the specified zone
actually exists before attempting to create the bucket in it.
Fixes #177.

sos: create: check user-specified zone

---

cmd/root.go

There was a panic when the `EXOSCALE_ACCOUNT` environment variable was set. 
This was caused by a call to [FlagSet.Lookup](https://godoc.org/github.com/spf13/pflag#FlagSet.Lookup) which returned `nil` because the flag name was incorrect leading to a `nil pointer dereference`.

Fix panic when EXOSCALE_ACCOUNT environment variable is set

---

.goreleaser.yml
.travis.yml

- bump versions
- latest goreleaser doesn't need rpm

travis: build on go 1.13

---

cmd/sos.go
cmd/sos_acl.go
cmd/sos_create.go
cmd/sos_delete.go
cmd/sos_download.go
cmd/sos_headers.go
cmd/sos_list.go
cmd/sos_metadata.go
cmd/sos_remove.go
cmd/sos_upload.go
go.mod

This change introduces a workaround to a bug in the Microsoft Windows
support in Go (https://github.com/golang/go/issues/16736). Some
heavily-chained certificates such as Exoscale SOS API's one are not
recognized as being signed by a trusted Certificate Authority.
Until the bug is fixed upstream, Windows users are required to use the
`--certs-file` flag with a path to a local file containing Exoscale SOS
API's certificate chain to the `exo sos` commands.
Fixes #189.

sos: fix TLS certificate issue on Windows

---

cmd/vm_show.go

Currently the `exo vm show` command doesn't show the Private Networks the instance is attached to, although this information is show in the portal equivalent view.

Show Private Networks in "exo vm show" (ch-6418)

---

cmd/instance_pool_show.go

This change fixes the `exo instancepool show` command output ("Private
Networks" instead of "Privnets").

Fix "instancepool show" command output

---

cmd/config.go
cmd/iam_apikey_create.go
cmd/iam_apikey_revoke.go

This PR removes the function of being able to add an API key in the config file after its creation & adds the function of adding a restricted API key in the config file with the command `exo config`

bug: adding a restricted key to config

---

cmd/iam_apikey_operations.go

This PR changes the output of the `exo iam apikey operations` command.
lower case --> camel case
```
% exo lab iam apikey operations "iam"
┼─────────┼──────────────────────────┼
│ Compute │ n/a                      │
│ DNS     │ n/a                      │
│ IAM     │ iam/*                    │
│         │ iam/createApiKey         │
│         │ iam/getApiKey            │
│         │ iam/listApiKeyOperations │
│         │ iam/listApiKeys          │
│         │ iam/revokeApiKey         │
│ SOS     │ n/a                      │
┼─────────┼──────────────────────────┼
```

fix: "iam apikey operations" command output

---

cmd/config.go
cmd/config_add.go
cmd/config_delete.go
cmd/config_list.go
cmd/config_set.go

This change introduces an explicit `exo config add` command allowing
users to create a CLI configuration accounts. Includes some light
internal refactoring to make code more readable.
```console
$ ./exo config add blah
[+] API Key [none]: EXOxxxxxxxxxxxxxxxxxxxxxxx
[+] Secret Key [none]: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Retrieving account information... done!
[+] Name [xxxxxx@exoscale.com]: blah
✔ ch-gva-2
You chose "ch-gva-2"
[+] Set [blah] as default account? [yN]: y
$ ./exo config
To configure a new account, run `exo config add`
Use the arrow keys to navigate: ↓ ↑ → ←
? Configured accounts (* = default account):
▸ alice
bob
carl
blah*
```

config: add a dedicated account creation command

---

go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/iam_apikey.go
vendor/github.com/exoscale/egoscale/version.go
vendor/modules.txt

This change upgrades the egoscale dependency to version 0.20.1, fixing a change in IAM API response format.

mod: upgrade egoscale to 0.20.1

---

cmd/sos_show.go

This PR add a new SOS command.
- `sos show`
```
%exo sos show
Usage:
exo sos show <bucket name> <oject name> [flags]
Aliases:
show, get
Flags:
-h, --help   help for show
Global Flags:
--certs-file string        Path to file containing additional SOS API X.509 certificates
-C, --config string            Specify an alternate config file [env EXOSCALE_CONFIG]
-O, --output-format string     Output format (table|json|text)
--output-template string   Template to use if output format is "text"
-Q, --quiet                    Quiet mode (disable non-essential command output
-A, --use-account string       Account to use in config file [env EXOSCALE_ACCOUNT]
```
```
%exo sos show test T-DOP-600_ansible.pdf
┼───────────────────────┼─────────────────────────────────────────────────────────────┼
│ …
```

add sos show command

---

cmd/sos.go

Trace on minio when `EXOSCALE_TRACE`  env is set

SOS: Add EXOSCALE_TRACE to log sos operations

---

cmd/sos_acl.go

In an overwhelming majority of cases, users setting ACLs to
--public-read or --public-read-write will want to share the link to that
ressource via HTTP.
This saves the users a couple of clicks by printing the link to the file
they just uploaded to stdout.
No other canned ACLs are impacted.
Example run:
```
$ ./exo sos acl add sharing-is-caring blah.jpg --public-read
https://sos-ch-dk-2.exo.io/sharing-is-caring/blah.jpg
```

Print SOS link when adding canned public ACL

---

cmd/instance_pool.go

Since instance pools are now generally available, they don't need to sit
behind the "lab" section of the CLI tool.

Graduate instancepool to a non-lab feature.

---

cmd/iam_apikey_operations.go

this PR adds the listing of the available account operations of an API key.

[iam apikey operations] add account operations

---

cmd/sos.go
cmd/sos_create.go

This PR removed the listZones call in `exo sos create` & used the account defaultZone (if it possible) in newSOSClient

[sos] remove the listZones call

---

.travis.yml
Dockerfile
cmd/root.go

This should fix failures to find the config file's location on
Windows. As per a recommendation from @greut, thanks!
Somewhat related to #197 though it might not fix the issue.

use go 1.13 and rely on os.UserConfigDir to find config location

---

cmd/config.go
cmd/config_add.go
cmd/root.go

This change improves the UX of listing configured accounts and adds a
new shortcut to create a new one directly from the list.
Also fixes a bug where a non-existent account name would not be detected
properly.
```console
$ ./exo config
Use the arrow keys to navigate: ↓ ↑ → ←
? Configured accounts (* = default account):
▸ alice*
bob
<Configure a new account>
```

config: improve account listing UX

---

cmd/root.go

This change adds an explicit reference to the `exo output --help`
internal reference to custom output usage documentation.

help: add explicit reference to custom output doc

---

cmd/config.go
cmd/config_add.go
cmd/config_set.go
cmd/zone.go

This change improves the UX of account creation when using IAM
restricted keys preventing us to retrieve the information matching the
API credentials provided by the user: instead of prompting the user with
a free-form text input for the zone, we offer a selection using
built-in zones list.

config: improve account creation with restricted keys

---

cmd/kube_create.go

Bump calico version to 3.12.0 and update URLs of calico's manifest.
This should fix issue #224
```bash
./exo lab kube create bundes                                                                                                                       <<<
Creating private SSH key
Deploying "bundes" ⠼                                                                                done!
Bootstrapping Kubernetes cluster (can take up to several minutes):
Instance system upgrade... success!
Docker Engine installation... success!
Kubernetes cluster node installation... success!
Kubernetes cluster node initialization... success!
Your Kubernetes cluster is ready. What do now?
1. Install the "kubectl" command, if you don't have it already:
https://kubernetes.io/docs/tasks/tools/install-kubectl/
2. …
```

Bump calico version to 3.12.0

---

Dockerfile

As Ubuntu 18.10 is EOL, we can't install packages using exoscale/cli as base image because Ubuntu mirrors are not available anymore.

Use non EOL Ubuntu as based distro

---

cmd/request.go
cmd/template_register.go
cmd/template_show.go

This change adds support for `vm template register` command output
customization via the global `--output-format` flag. Also, async
commands output support messages (e.g. command waiter message &
termination status) are now written to stderr instead of stdout so
that they can be discarded independently from standard commands
output.

template register: support output customization

---

cmd/affinitygroup_create.go
cmd/affinitygroup_show.go
cmd/iam_apikey_create.go
cmd/privnet_create.go
cmd/privnet_show.go
cmd/privnet_update.go
cmd/snapshot_create.go
cmd/snapshot_delete.go
cmd/snapshot_show.go
cmd/sshkey_create.go
cmd/sshkey_upload.go

This change adds support for output customization through the use of
global `--output-format` flag to all `create|add` commands when possible.

Add output customization to create commands

---

.goreleaser.yml

This PR enables to run `exo` binary on ARM 6 and ARM 7 (A-xx ) series for 32 bits as well as ARM 64 bits
tested to run on Raspbian, Armbian and similar

add releases for arm 32 and 64 bits

---

cmd/iam_apikey.go
cmd/iam_apikey_create.go
cmd/iam_apikey_list.go

This change improves the UX of the `iam apikey` commands:
- Sort operations list in alphabetical order
- Don't display the operations in the `apikey list` view, as a long list
of operations produces ugly results

iam: improve apikey commands output UX

---

cmd/config.go

This change fixes a bug where the configuration account selector would
prompt for a new account input where the user selects the account that
is already the default account in the list (i.e. no change).

config: fix account selector

---

snap/snapcraft.yaml

This change fixes the Snapcraft packaging method which was broken since
the switch to go.mk.
```console
$ snapcraft
Pulling exo
Building exo
Submodule 'go.mk' (https://github.com/exoscale/go.mk.git) registered for path 'go.mk'
Cloning into '/home/marc/cli/parts/exo/build/go.mk'...
Submodule path 'go.mk': checked out '5b6c0ef1a35e89820cdfb6c62ce4514ac86d240f'
make build -j1
test -d /home/marc/cli/parts/exo/build/bin || mkdir /home/marc/cli/parts/exo/build/bin
test -d vendor || mkdir vendor
go mod vendor
/snap/bin/go build                                       \
\
-ldflags "-X main.commit=4b82b89 -X main.branch=master -X main.buildDate=2020-05-05T08:06:07+0000 -X main.version=1.12.0"                                \
\
-mod vendor                         \
-o …
```

Fix Snapcraft packaging

---

cmd/root.go

This change fixes how the client's User Agent is set, ensuring it will
actually always be set.

Fix client User Agent setting

---

.goreleaser.yml
CHANGELOG.md
Makefile
cmd/sos.go

This pull request implements checking the directory of the `exo` binary for a file named `sos-certs.pem` and load that if no `--certs-file` flag has been supplied.
This works around golang/go#16736 which prevents `exo sos` commands from working without explicitly passing a certificate chain.
~~Note that the build system still needs to be adapted to bundle `sos-certs.pem` into the ZIP file on Windows.~~
A separate PR #245 has been submitted as well which only warns the user.

Make certificates work on Windows again

---

cmd/snapshot_export.go

```
exo vm snapshot export f5860e58-fa71-48b1-9724-4b4c3a3759b5 --download ./
Exporting snapshot "f5860e58-fa71-48b1-9724-4b4c3a3759b5". success
Downloading snapshot file. 6.20 MiB / 452.12 MiB [>-------------------------------------------------------------| 3m16s ]
ls *.qcow2
f5860e58-fa71-48b1-9724-4b4c3a3759b5.qcow2
```
```
exo vm snapshot export f5860e58-fa71-48b1-9724-4b4c3a3759b5 --download template.qcow2
Exporting snapshot "f5860e58-fa71-48b1-9724-4b4c3a3759b5". success
Downloading snapshot file. success
Verifying downloaded file checksum. success
ls *.qcow2
template.qcow2
```

vm: snapshot export: add flag --download

---

cmd/ssh.go
go.mod
go.sum
vendor/github.com/kballard/go-shellquote/LICENSE
vendor/github.com/kballard/go-shellquote/README
vendor/github.com/kballard/go-shellquote/doc.go
vendor/github.com/kballard/go-shellquote/quote.go
vendor/github.com/kballard/go-shellquote/unquote.go
vendor/modules.txt

This change introduces a new `--ssh-options|-o` flag to the `exo ssh`
command, allowing users to provide additional flags that will be passed
as-is to the shelled out `ssh` command.
```console
$ ./bin/exo ssh my-vm
Warning: Identity file /Users/marc/.exoscale/instances/ce282813-2bc4-4429-88bc-2676f01a1227/id_rsa not found or not accessible.
The authenticity of host '194.182.160.142 (194.182.160.142)' can't be established.
ECDSA key fingerprint is SHA256:LlaRHTXat/GKKRgbbUBorIAke2QpODnaYATbjHkAe2g.
Are you sure you want to continue connecting (yes/no)? ^Cerror: signal: interrupt
$ ./bin/exo ssh -o "-o StrictHostKeyChecking=no" my-vm
Warning: Identity file /Users/marc/.exoscale/instances/ce282813-2bc4-4429-88bc-2676f01a1227/id_rsa not found or not accessible.
Warning: Permanently added …
```

ssh: add "--ssh-options" flag

---

cmd/sos_download.go
cmd/sos_download_test.go

Adds a flag to `exo sos download` which will skip the file existence check.
It's off by default.
There are scenarios where this is valid behaviour.
Slightly related: I think that the `os.Rename` step at https://github.com/exoscale/cli/compare/sos-download-overwrite?expand=1#diff-cbe63d0320814a34674804f20dcfac94R140 does not take into account the case where `localFilePath` is a directory, and thus needs to be appended with `objectName`.

feat(sos-download): Add flag that allows overwriting the destination

---

cmd/config.go
cmd/environment.go
cmd/root.go

This change introduces a new `exo environment` command describing the
supported environment variables and their behavior, as well as an
undocumented `exo env` command that can be used to export environment
variables using the configured account profiles.

Add "exo environment" documentation command

---

cmd/instance_pool_create.go
cmd/instance_pool_update.go
cmd/vm.go
cmd/vm_create.go
cmd/vm_edit.go
cmd/vm_show.go
cmd/vm_update.go

This change introduces a new `exo vm update` command enabling users to
edit some Compute instance properties, such as the display/hostname and
the cloud-init user data.
Besides, a new `exo vm show --user-data` flag now returns the current cloud-init user data configuration of a Compute instance.

vm: new "update" command

---

cmd/ssh.go
cmd/vm_create.go

This change fixes a bug in the SSH-related sections of the CLI, where an
error message was reported when dealing with Compute instances based on
a custom template for which a username is not set in its metadata
(setting a username is not mandatory).
Before:
$ exo ssh --print my-instance
error: missing username information in Template "58f032e5-20db-425c-8108-37f0b764cd1a"
After:
$ exo ssh --print my-instance
ssh -i "/Users/marc/.exoscale/instances/8bc37224-03af-46c5-9e30-ca4cac62a887/id_rsa" 159.100.242.169
And for instances using a template specifying a username:
$ exo ssh --print vm
ssh -i "/Users/marc/.exoscale/instances/811d7ce7-b8e8-401c-b9ed-797859e885f0/id_rsa" -l ubuntu 185.19.29.144
Also, a bit of refactoring in `ssh` related commands.

ssh: fix bug with username-less templates

---

cmd/root.go

Using `filepath` is more appropriate to manipulate file, folder...etc. instead of `path`
This PR solve the issue on Windows to create the Exoscale CLI configuration in the correct directory.

Fix Windows configuration path

---

cmd/config.go
cmd/config_add.go
cmd/config_delete.go
cmd/config_set.go
cmd/config_show.go
cmd/root.go

This change fixes a bug where the `exo x` subcommand's config registry
settings where leaking into the main CLI's one.

config: fix subcommand config settings leaking

---

cmd/internal/x/x.go

This change cleans up the mess left by openapi-cli-generator used in
`exo x` subcommands.

x: clean unused config cache

---

Dockerfile
Makefile

This PR referring to https://github.com/exoscale/cli/pull/254, to make the docker image size smaller.
Fix #254

Dockerfile: Make Docker image smaller

---

Dockerfile

The alpine base image still provides a shell in the container. This
makes it much easier to use the image in a CI environment or as an init
container in a k8s pod.
The added utility should be worth the extra 6Mb in image size.
```
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
cli                                test                d9c1593fd3bf        5 minutes ago       26.7MB
exoscale/cli                       latest              ec194dd39256        19 hours ago        20.8MB
```

refactor: Use alpine as cli base image

---

cmd/ssh.go

This change fixes a bug in the `exo ssh` command where the path to the
SSH private key was misquoted, resulting in the generated ssh command
not able to use the file.

ssh: fix bogus SSH private key file quoting

---

cmd/nlb.go
cmd/nlb_create.go
cmd/nlb_delete.go
cmd/nlb_service_add.go
cmd/nlb_service_delete.go
cmd/nlb_service_show.go
cmd/nlb_service_update.go
cmd/nlb_show.go
cmd/nlb_update.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/loadbalancer.go
vendor/github.com/exoscale/egoscale/version.go
vendor/modules.txt

This change improves the `exo nlb` commands by allowing users to
reference NLB instances (and services) by their name or ID.

nlb: support referencing resources by name or ID

---

cmd/nlb_create.go
cmd/template_register.go

```
exo vm template register test --from-snapshot 6804dd0f-d33f-49fc-a153-ecd74095575a
Exporting snapshot "6804dd0f-d33f-49fc-a153-ecd74095575a". success
Registering the template............................. success
┼───────────────┼──────────────────────────────────────┼
│   TEMPLATE    │                                      │
┼───────────────┼──────────────────────────────────────┼
│ ID            │ 5950d719-e81e-47b0-83ff-f6ffbdcb438b │
│ Name          │ test                                 │
│ OS Type       │ Other (64-bit)                       │
│ Creation Date │ 2020-07-09T09:48:30Z                 │
│ Zone          │ ch-dk-2                              │
│ Disk Size     │ 50 GiB                               │
│ Username      │                                      │
│ Password? …
```

template register: Add --from-snapshot flag & change --name flag to an argument

---

.goreleaser.yml
Dockerfile.goreleaser

This change updates the GoReleaser configuration to build and release
the `exoscale/cli` Docker image to the Docker hub.

Release exoscale/cli Docker image with GoReleaser

---

cmd/cmd.go
cmd/ssh.go
cmd/vm_delete.go
cmd/vm_firewall.go
cmd/vm_list.go
cmd/vm_reboot.go
cmd/vm_reset.go
cmd/vm_resize.go
cmd/vm_scale.go
cmd/vm_show.go
cmd/vm_start.go
cmd/vm_stop.go
cmd/vm_update.go

This change introduces dynamic CLI argument auto-completion for `exo vm *`
commands (and `exo ssh`) with the current user's Compute instance names:
[![asciicast](https://asciinema.org/a/7IcN1UacbwtHoZFLr8Fi4TnYK.svg)](https://asciinema.org/a/7IcN1UacbwtHoZFLr8Fi4TnYK)

Add dynamic names autocompletion for VM-related commands

---

cmd/template.go

This change disables the name-based filtering performed on
"non-standard" templates in the `exo vm template list` command, allowing
the CLI to return the actual list of custom templates belonging to a
user/org.
Fixes #149.

template list: don't de-dup custom templates

---

cmd/privnet_show.go

This change add display of a Private Network's description in the `exo
privnet show` command output.

privnet: show description in "show" command output

---

cmd/request.go

This change prints the output of asynchronous operations to `stderr`
instead of `stdout` by default, so that users can discard those using
`2>/null` and still use the `--output|-O` flag to retrieve information
after operation completion.

Write async operation output to stderr

---

README.md
cmd/config.go

This is a proposal to align documentation to best practices regarding API credentials:
* redirect users to IAM instead of ACCOUNT section which is deprecated
* point to the correct configuration path

documentation fixes for exo config

---

cmd/sos.go

This change fixes a bug in zoned SOS commands, where the zone endpoint
was be incorrectly constructed in some contexts (e.g. non-production
environments).

sos: fix endpoint construction

---

cmd/affinitygroup.go
cmd/cmd.go
cmd/coi.go
cmd/firewall.go
cmd/instance_pool_create.go
cmd/kube_create.go
cmd/privnet.go
cmd/serviceoffering.go
cmd/template.go
cmd/vm_create.go
cmd/vm_show.go
cmd/zone.go

This change refactors the `vm create` command implementation to support
global `--output` flag:
```command
$ go run main.go vm create blah --disk 10 -O json | jq .
Creating single-use SSH key
Deploying "blah" ⠴                                       done
{
"id": "d5c46409-5c4e-4269-995a-2395bbca8128",
"name": "blah",
"creation_date": "2020-11-16T09:11:58+0100",
"size": "Medium",
"disk_size": "10 GiB",
"template": "Linux Ubuntu 20.04 LTS 64-bit",
"zone": "ch-gva-2",
"state": "Running",
"ip_address": "159.100.241.155",
"username": "ubuntu",
"ssh_key": "/Users/marc/Library/Application Support/exoscale/instances/d5c46409-5c4e-4269-995a-2395bbca8128/id_rsa",
"security_groups": [
"default"
]
}
```
Besides, the command now only supports creating a single instance to make it more consistent with …

vm: support custom output for "create" command

---

cmd/limits.go

```
❯ exo vm template list --mine -z de-fra-1
┼──────────────────────────────────────┼──────┼──────────────────────────┼──────────┼───────────┼
│                  ID                  │ NAME │      CREATION DATE       │   ZONE   │ DISK SIZE │
┼──────────────────────────────────────┼──────┼──────────────────────────┼──────────┼───────────┼
│   4b71cc-8bee-4354-953e-18bb10bc0027 │ test │ 2020-11-27T11:19:32+0100 │ de-fra-1 │ 50 GiB    │
┼──────────────────────────────────────┼──────┼──────────────────────────┼──────────┼───────────┼
```
(only one template)
before:
```
❯ exo limits
┼──────────────────┼──────┼─────┼
│     RESOURCE     │ USED │ MAX │
┼──────────────────┼──────┼─────┼
│ Templates        │ 0    │ 30  │
│ Instances        │ 0    │ 4   │
│ Snapshots        │ 0    │ 30  │
│ Private …
```

fix: limits: display template used

---

cmd/sos_upload.go

For multipart uploads, this triggers this code path:
https://github.com/minio/minio-go/blob/v6.0.57/api-put-object-streaming.go#L278
For non-multipart, this code path:
https://github.com/minio/minio-go/blob/v6.0.57/api-put-object-streaming.go#L384
This results in put requests being done with a `Content-MD5` header,
allowing the client and the backend to agree on data integrity.

sos upload: always send content md5

---

cmd/sks_create.go

Small typo, `clsuter` -> `cluster`

sks: fix typo

---

snap/snapcraft.yaml

The Exoscale Terraform provider looks for credentials in `$HOME/.cloudstack.ini`. Would be cool if the Exoscale CLI followed this convention. Currently, Exoscale CLI fails as follows:
```
$ exo config
No Exoscale CLI configuration found
error: open /home/cklein/.cloudstack.ini: permission denied
$ exo version
exo 1.22.2 df6255d (egoscale 0.37.1)
```

Allow access to $HOME/.cloudstack.ini

---

cmd/vm_firewall.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/version.go
vendor/github.com/exoscale/egoscale/virtual_machines.go
vendor/github.com/stretchr/testify/assert/assertion_compare.go
vendor/github.com/stretchr/testify/assert/assertion_format.go
vendor/github.com/stretchr/testify/assert/assertion_forward.go
vendor/github.com/stretchr/testify/assert/assertion_order.go
vendor/github.com/stretchr/testify/assert/assertions.go
vendor/github.com/stretchr/testify/mock/mock.go
vendor/modules.txt

This change updates the `exo vm firewall *` commands to use the new
`updateVirtualMachineSecurityGroups` API call allowing SG membership
edition without stopping Compute instances.

vm: firewall: support rebootless API call

---

cmd/sks_nodepool_evict.go

This changes fixes a bug in the `exo sks nodepool evict` command
arguments parsing, where an "invalid arguments" error would be returned
in the legitimate case of a single Node passed.

sks: fix "nodepool evict" arguments parsing issue

---

cmd/sks.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/.gitignore
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/client.go
vendor/github.com/exoscale/egoscale/version.go
vendor/modules.txt

This change fixes the client timeout extension for the `exo sks`
commands.

sks: fix timeout extension

---

cmd/sks_kubeconfig.go

This change adds support for usage of the `exo sks kubeconfig` command
in credential plugin mode, where it returns a kubeconfig `user` data
dynamically to the `kubectl` CLI.
Fixes #322.

sks: kubeconfig: add support for exec credential mode

---

.golangci.yml
cmd/storage.go
cmd/storage_download.go

This change fixes the listing logic used in the `exo storage` commands,
where previously all objects matching the specified prefix were
processed – which is not wanted when the prefix points to a discrete
file. The updated logic returns only the object matching the specified
prefix if the prefix doesn't end with a trailing separator ("/").
This change fixes the behavior of the `exo storage download` command,
where previously downloading a file located in a prefix would re-create
the prefix directory tree locally. The updated logic now stores the
specified file under its base name in the specified local directory.
This change fixes a bug causing a "file already exists" error message
returned when users pass a destination as relative path (e.g. ".", "..",
"../..") without trailing slash.

storage: bug fixes

---

cmd/storage_metadata_add.go

This change fixes a crashing issue when a user attempted to set metadata
on an object that doesn't have any metadata set yet.
This change hardens the `metadata add` command by validating provided
metadata keys to prevent the use of invalid characters.

storage: various metadata bug fixes

---

cmd/sks_create.go

This change deploys the Kubernetes Metrics Server cluster add-on by
default in the `exo sks create` command.

sks: deploy K8s Metrics Server add-on by default

---

cmd/environment.go

This change adds a new flag `-u|--unset` to the `exo env` command,
allowing removal of the environment variables set by the `exo env`
command.

env: support variables unsetting

---

cmd/storage_show.go

This change re-introduces the SOS URL to be displayed for objects
in the `exo storage show` command.

storage: show: add object URL

---

cmd/sks_nodepool_add.go
cmd/sks_nodepool_show.go
cmd/sks_nodepool_update.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/client.go
vendor/github.com/exoscale/egoscale/v2/client.go
vendor/github.com/exoscale/egoscale/v2/instance.go
vendor/github.com/exoscale/egoscale/v2/instance_type.go
vendor/github.com/exoscale/egoscale/v2/internal/public-api/public-api.gen.go
vendor/github.com/exoscale/egoscale/v2/internal/public-api/sks_nodepool.go
vendor/github.com/exoscale/egoscale/v2/internal/public-api/snapshot.go
vendor/github.com/exoscale/egoscale/v2/sks.go
vendor/github.com/exoscale/egoscale/version.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This change adds support for specifying Instance Prefix and Deploy
Target on SKS Nodepools.

sks: add support for Instance Prefix/Deploy Target to Nodepools

---

cmd/instance_pool_evict.go

This change fixes a bug preventing the `exo instancepool evict` command
from working as expected.

instancepool: fix a bug in the "evict" command

---

.goreleaser.yml
Makefile
completion/main.go

This change adds shell autocompletion support for Fish, PowerShell &
Zsh.

Add autocompletion generation for more shells

---

cmd/firewall_add.go
cmd/flags.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/security_groups.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This change allows users to specify ICMP code/type -1 when adding new
firewall rules.

firewall: support ICMP SG rules with code/type -1

---

cmd/db_type_list.go
cmd/db_type_show.go
cmd/util.go

This change fixes as crashing bug occuring during `exo lab db types
list|show` commands.

lab: db: fix crash during types list/show

---

cmd/sks_create.go
cmd/sks_nodepool_add.go
cmd/sks_nodepool_show.go
cmd/sks_nodepool_update.go
cmd/sks_show.go
cmd/sks_update.go

This change adds support for labels to SKS clusters/nodepools, as well
as auto-upgrade for SKS clusters.

sks: add support for labels/auto-upgrade

---

cmd/instance_show.go

This change adds the missing Compute instance IP address field to the
output of the `exo compute instance show` command.

Add missing IP address in "exo compute instance show"

---

cmd/instance_type.go
cmd/instance_type_list.go
cmd/instance_type_show.go

This change adds new `exo compute instance-type *` commands.

compute: add "instance-type" commands

---

cmd/sks_nodepool_add.go
cmd/sks_nodepool_show.go
cmd/sks_nodepool_update.go

This change adds support for Private Networks to the `exo sks nodepool`
commands via the `--private-network` flag.

sks: nodepool: add support for Private Networks

---

cmd/instance_template_list.go

This change fixes a bug in the `exo compute instance-template list`
command, where the `--zone` flag value would be ignored and templates
would always be listed in the current account's default zone.

compute: instance-template: fix "list" command

---

cmd/db_cacertificate.go
cmd/db_service_create.go
cmd/db_service_delete.go
cmd/db_service_list.go
cmd/db_service_show.go
cmd/db_service_update.go
cmd/db_type_list.go
cmd/db_type_show.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/database.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This change adds a new `exo lab db get-certificate` command.
This change introduces a new `ConnectionInfo` output label to the `exo
lab db show` command, exposing service-specific connection info.
This change introduces a new `Components` output label to the `exo
lab db show` command, exposing service-specific components.

db: new "ca-certificate" command + connection info output label

---

cmd/db_service_show.go

This change changes the `exo lab db service show` output format for the
`.Users` property, exposing more information.

lab: db: show: change .Users property format

---

cmd/sks_upgrade_service_level.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/sks.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This change adds a new `exo sks upgrade-service-level` command.

sks: add new "upgrade-service-level" command

---

cmd/vm_create.go

This change fixes a bug displaying the `error: multiple Compute
instances found, specify an ID instead` message after creating a Compute
instance sharing the same name as an existing one.

vm: fix a bug in the "create" command

---

cmd/firewall.go
cmd/firewall_list.go
cmd/firewall_show.go
cmd/security_group.go
cmd/security_group_create.go
cmd/security_group_delete.go
cmd/security_group_list.go
cmd/security_group_rule.go
cmd/security_group_rule_add.go
cmd/security_group_rule_delete.go
cmd/security_group_show.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/security_group.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This change adds new `exo compute security-group *` and deprecates
`exo firewall *` commands.

compute: add new "security-group" commands

---

cmd/affinitygroup.go
cmd/anti_affinity_group.go
cmd/anti_affinity_group_create.go
cmd/anti_affinity_group_delete.go
cmd/anti_affinity_group_list.go
cmd/anti_affinity_group_show.go
cmd/deploy_target.go
cmd/security_group.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/anti_affinity_group.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This change adds new `exo compute anti-affinity-group *` and deprecates
`exo anti-affinity-group *` commands.

compute: add new "anti-affinity-group" commands

---

cmd/private_network_delete.go
cmd/private_network_list.go
cmd/private_network_show.go

This change adds the resource zone to the output of `exo compute
private-network list|show` commands.

compute: private-network: display zone in command output

---

cmd/client.go
cmd/instance_pool.go
cmd/instance_pool_create.go
cmd/instance_pool_evict.go
cmd/instance_pool_scale.go
cmd/instance_pool_show.go
cmd/instance_pool_update.go
cmd/sks_nodepool_evict.go
cmd/sks_nodepool_scale.go

*  compute: instance-pool: deprecate flags
This change deprecates the `--disk`/`--service-offering` from the
`exo compute intance-pool (create|update)` commands, replaced with
`--disk-size`/`--instance-type`.
* Set default client timeout to 5 minutes
* compute: alias "exo compute instance-pool"
This change adds a new convenience alias `exo compute pool` for
`exo compute instance-pool`.
* compute: instance-pool: rename template label
This change renames the `.ServiceOffering` label from the `exo compute
instance-pool show` command into `.InstanceType`.

Deprecations and various fixes

---

cmd/instance_pool_create.go
cmd/instance_pool_update.go

This change deprecates the `--keypair`/`--privnet` from the
`exo compute intance-pool (create|update)` commands, replaced with
`--ssh-key`/`--private-network`.

compute: instance-pool: deprecate flags

---

cmd/instance_snapshot_export.go
cmd/instance_snapshot_revert.go

This change adds the `exo compute instance snapshot revert` command.

compute: instance: snapshot: add "revert" command

---

cmd/instance.go

This change raises the default timeout for Compute instance operations
to 10 minutes.

compute: instance: raise default timeout

---

cmd/client.go
cmd/x.go

This change fixes a bug causing the client custom HTTP User-Agent header
not to be set on outgoing API requests.

Fix client custom HTTP User-Agent header

---

cmd/limits.go

This change rewrites the `exo limits` command to retrieve limits
information from the Exoscale public API (V2).

limits: switch to public API

---

cmd/instance_template_register.go

This change fixes a bug preventing users to use the `exo compute
instance-template register` command without passing
`--disable-(password|ssh-key)` flags.

Fix Compute instance template registration command

---

cmd/instance_create.go

This change fixes a bug in the `exo compute instance create` command,
where the CLI would crash if the user provides the `--private-network`
flag.
Fixes #400

Fix "exo compute instance create" command

---

cmd/dbaas_service_create_pg.go

This change fixes a bug in the `exo dbaas create` command, where the use
of the `--pg-bouncer-settings` flag would return a JSON validation error
message.

Fix a bug in the "exo dbaas create" command

---

cmd/dbaas_create.go
cmd/dbaas_update.go

This change documents the proper `exo dbaas (create|update)
--termination-protection` flag usage.

dbaas: update termination protection flag help

---

cmd/dbaas_type_list.go

This change fixes the output of the `exo dbaas type list` command's
"Available Versions" column.

dbaas type list: fix available versions output

---

cmd/instance_pool_create.go
cmd/instance_pool_delete.go
cmd/instance_pool_evict.go
cmd/instance_pool_list.go
cmd/instance_pool_scale.go
cmd/instance_pool_show.go
cmd/instance_pool_update.go
cmd/nlb_create.go
cmd/nlb_delete.go
cmd/nlb_list.go
cmd/nlb_show.go
cmd/nlb_update.go
cmd/sks_authority_cert.go
cmd/sks_create.go
cmd/sks_delete.go
cmd/sks_kubeconfig.go
cmd/sks_list.go
cmd/sks_rotate_ccm_credentials.go
cmd/sks_show.go
cmd/sks_update.go
cmd/sks_upgrade.go
cmd/sks_upgrade_service_level.go
cmd/sks_versions.go

This change fixes a bug crashing deprecated commands using the automatic
CLI commands generation helper.

Fix crash in deprecated commands

---

cmd/limits.go

This change adds a dedicated quota entry for the Network Load Balancers
in the `exo limits` command output.

limits: add entry for NLBs

---

go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/oapi/oapi.gen.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This change fixes a crashing bug occurring when running the `exo dbaas show`
command with a Database Service of type `pg` featuring stand-by nodes.

dbaas show: fix a crash with pg-type services

---

cmd/iam_access_key.go
cmd/iam_access_key_create.go
cmd/iam_access_key_list.go
cmd/iam_access_key_listoperations.go
cmd/iam_access_key_revoke.go
cmd/iam_access_key_show.go
cmd/iam_apikey.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/iam_access_key.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This change introduces new `exo iam access-key *` commands using the new
IAM v2 API, deprecating the `exo iam apikeys *` commands.

Add new "exo iam access-key *" commands

---

cmd/sks_create.go

This change fixes a crashing bug occurring when creating an SKS cluster
with a default Nodepool without specifying a name using the
--nodepool-name` flag.

compute sks: fix a crash in the "create" command

---

cmd/dbaas_logs.go

This changes fixes a bug causing the `exo dbaas logs` command to crash
if the Database Service is too recent to have logs.

dbaas: fix a crash in the "logs" command

---

cmd/sks_create.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/oapi/oapi.gen.go
vendor/github.com/exoscale/egoscale/v2/sks_cluster.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This change switches the `exo compute sks create --oidc-required-claim`
flag type from `string` to `map[string]string` following an API change.

compute sks create: change --oidc-required-claim flag type

---

cmd/instance_template_register.go

This change fixes a bug in the `exo compute instance-template register`
command, preventing to use the `--from-snapshot` flag.

compute instance-template register: fix --from-snapshot

---

cmd/cmd.go
cmd/instance_create.go
cmd/instance_pool_create.go
cmd/instance_reset.go

In `exo compute instance create` and `exo compute instance-pool create`, the current active account's default template will be used instead of the CLI one (if `--template` flag is absent).

compute instance: Use defaultTemplate from current account (fix #428)

---

.goreleaser.yml
Makefile

- Default make shell might not be bash so we should avoid expansion.
- The builds are running in parallel, including the build hook, this caused concurency issues for me so I moved the hook before the build
testing: 1.50.0 released from this branch

Fix brace expansion in Makefile and concurency issue in goreleaser

---

cmd/sks_deprecated_resources.go
cmd/sks_upgrade.go
cmd/util.go

Requires https://github.com/exoscale/egoscale/pull/551
Features (with Kubernetes 1.22):
Cluster deprecated resources listing:
```
➜ go run main.go compute sks deprecated-resources -z de-fra-1 test-upgrade
┼────────┼─────────┼──────────────────────┼──────────────┼─────────────────┼
│ GROUP  │ VERSION │       RESOURCE       │ SUB RESOURCE │ REMOVED RELEASE │
┼────────┼─────────┼──────────────────────┼──────────────┼─────────────────┼
│ policy │ v1beta1 │ poddisruptionbudgets │              │ 1.25            │
│ policy │ v1beta1 │ podsecuritypolicies  │              │ 1.25            │
┼────────┼─────────┼──────────────────────┼──────────────┼─────────────────┼
```
Cluster upgrade warning:
```
➜ go run main.go compute sks upgrade -z de-fra-1 test-upgrade 1.23        
Some resources in your …
```

Implement SKS deprecated resources listing

---

.github/workflows/main.yml
Makefile

The recent modification to the Makefile enforces downloading a
source document which is inconvenient while working on new API
functionality.
This patch allows downloading by default but will also let
developers supply their own document if necessary.

makefile: allow supplying an alternative OpenAPI document

---

.golangci.yml

This change replaces deprecated linter with recommended alternative (`revive`). Also updates `go.mk` submodule.

golangci-lint: use revive instead of golint & update go.mk

---

cmd/instance_create.go
cmd/instance_pool_create.go
cmd/instance_pool_update.go
cmd/instance_update.go
cmd/util.go
cmd/vm.go
cmd/vm_create.go
cmd/vm_show.go
cmd/vm_update.go

For some consistency with the Web portal, we should not compress the user-data by default.
In the context of the Fedora CoreOS template, Ignition accept only not compressed user-data:
https://github.com/coreos/ignition/pull/1345

Compute: Do not compress user-data by default

---

cmd/dbaas_type_show.go
cmd/output.go

New flag `--backup-config` prints backup configuration for service type and plan.
```
$ exo dbaas type show redis --help
....
Flags:
--backup-config string   show backup configuration for the Database Service type and Plan
-h, --help                   help for show
--plans                  list plans offered for the Database Service type
--settings string        show settings supported by the Database Service type
$ exo dbaas type show pg --backup-config startup-8 
┼────────────────────────────┼──────┼
│ Backup interval (hours)    │ 24   │
│ Max backups                │ 3    │
│ Recovery mode              │ pitr │
│ Frequent backup interval   │ n/a  │
│ Frequent backup max age    │ n/a  │
│ Infrequent backup interval │ n/a  │
│ Infrequent backup max age  │ n/a  │ …
```

dbaas type show: add --backup-config flag

---

cmd/instance_template_register.go

Large template registration can take more than 1h, this update allows one to specify a custom timeout.

Set template registration timeout customizable

---

cmd/sks_kubeconfig.go

The exo sks command seems to be deprecated, replace example usage with current API
Add zone to example usage because it is not obvious to specify a zone if a cluster is not in the default zone

Remove legacy example usage

---

cmd/dbaas_logs.go

fixes #443
The usage of the `--offset` parameter was unclear.
It takes an opaque offset identifier as parameter.
```
$ ./cli dbaas logs -h
This command outputs a Database Service logs.
|...]
Flags:
-h, --help            help for logs
-l, --limit int       number of log messages to retrieve (default 10)
-o, --offset string   opaque offset identifier (can be found in the JSON output of the command)
--sort string     log messages sorting order (asc|desc) (default "desc")
-z, --zone string     Database Service zone
[...]
```

Dbaas logs: Improve help for --offset

---

cmd/instance_list.go
cmd/instance_show.go
cmd/util.go

This change prevents the `exo compute instance list` command from panicking if an instance has no IP address (when an instance is created, during a short time, instance has no IP address).
```
┼──────────────────────────────────────┼──────────────────┼──────────┼─────────────────┼─────────────────┼─────────┼
│                  ID                  │       NAME       │   ZONE   │      TYPE       │   IP ADDRESS    │  STATE  │
┼──────────────────────────────────────┼──────────────────┼──────────┼─────────────────┼─────────────────┼─────────┼
│ a1d55bee-66fe-4847-bdce-fc7c50ce4411 │ test             │ ch-gva-2 │ standard.medium │ -               │ stopped │
┼──────────────────────────────────────┼──────────────────┼──────────┼─────────────────┼─────────────────┼─────────┼
```

instance list: fix panic when no ip

---

cmd/elastic_ip_create.go
cmd/elastic_ip_show.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/elastic_ip.go
vendor/github.com/exoscale/egoscale/v2/oapi/oapi.gen.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This PR adds supports for Elastic IPv6.
New flag `--ipv6` added to `compute elastic-ip create` command.
New fields in `compute elastic-ip show`: `Address Family` (inet4 or inet6) and `CIDR`.
Output of `compute elastic-ip list` unchanged.
```
$ go run . c elastic-ip create --ipv6 --description myip
✔ Creating Elastic IP... 3s
┼────────────────┼──────────────────────────────────────┼
│   ELASTIC IP   │                                      │
┼────────────────┼──────────────────────────────────────┼
│ ID             │ 429aca0f-9a30-4cb3-88da-808ff91bdd97 │
│ IP Address     │ 2a04:c43:e00:a127:500:1:0:1          │
│ Address Family │ inet6                                │
│ CIDR           │ 2a04:c43:e00:a127:500:1::/96         │
│ Description    │ myip                                 │
│ Zone …
```

elastic_ip: add support for IPv6

---

cmd/elastic_ip_create.go

Make it more clear that this flag creates an Elastic IPv6 prefix
not a single address.

elastic_ip: rephrase IPv6 flag help message

---

cmd/instance_list.go
cmd/instance_show.go
cmd/nlb_list.go
cmd/util.go

fixes #464
```
$ go run . compute nlb list
┼──────────────────────────────────────┼──────┼──────────┼────────────┼
│                  ID                  │ NAME │   ZONE   │ IP ADDRESS │
┼──────────────────────────────────────┼──────┼──────────┼────────────┼
│ 8148907c-7826-4957-8dfb-5f09beffb7a9 │ toto │ at-vie-1 │            │
│ 8148907c-7826-4957-8dfb-5f09beffb7a9 │ toto │ ch-gva-2 │            │
│ 8148907c-7826-4957-8dfb-5f09beffb7a9 │ toto │ ch-dk-2  │            │
│ 8148907c-7826-4957-8dfb-5f09beffb7a9 │ toto │ de-fra-1 │            │
┼──────────────────────────────────────┼──────┼──────────┼────────────┼
vs
$ exo compute nlb list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xfc315d]
goroutine …
```

Fix panic in nlb list if a NLB doesn't have an IP yet

---

CHANGELOG.md
cmd/nlb_show.go

fixes #471 and CHANGELOG for 1.59.2

Fix panic in nlb show if a NLB doesn't have an IP yet

---

cmd/config.go
cmd/root.go

Allow providing a "defaultOutputFormat" in the config file.  The command line argument still takes precedence.
Tested-by: Aaron Groom <aarongroom@users.noreply.github.com>

config: allow specifying a default output format

---

cmd/client.go
cmd/config.go
cmd/config_show.go
cmd/environment.go
cmd/root.go
go.mod
vendor/modules.txt

This PR adds `clientTimeout` configuration option (and `EXOSCALE_API_TIMEOUT` environment override) to set a egoscale API timeout. Extending API timeout is sometimes needed for async actions such as `instance_create`, `instance_pool_destroy`, etc.
Also extends default timeout from 5 minutes to 10 minutes.
```
$ go run . config show
┼──────────────────────────┼──────────────────────────────────────────────┼
│         ACCOUNT          │                                              │
┼──────────────────────────┼──────────────────────────────────────────────┼
│ Name                     │ my-account                                   │
│ API Key                  │ EXOxxxxxxxxxxxxxxxxxxxxxxxxx                 │
│ API Secret               │ ×××××××××××××××××××××××××××                  │
│ Default …
```

Add configuration parameter to set API timeout

---

cmd/storage_list.go

This PR implements delimiters for listing bucket objects (`exo storage list`).
By using a delimiter, listing large buckets will work much faster. Note that delimiter is not used with `--recursive` flag.

storage: leverage delimiter when listing objects

---

cmd/root.go

Fixes panic in the new feature ( #478 ) when credentials are set using environment variables.

Set default API timeout when env credentials are used

---

cmd/elastic_ip_show.go
cmd/elastic_ip_update.go
cmd/instance_show.go
cmd/instance_update.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/client_mock.go
vendor/github.com/exoscale/egoscale/v2/elastic_ip.go
vendor/github.com/exoscale/egoscale/v2/instance.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This PR implements a `--reverse-dns` flag to `compute instance` and `compute elastic-ip` commands.
Note: to delete a Reverse DNS entry, run update command with `--reverse-dns ""`.
```
$ go run . c i show update my-instance --reverse-dns example.net
✔ Updating instance "my-instance"... 3s
│ ID                   │ 27923f37-0b18-473e-a693-a10f907baf8d │
│ Name                 │ my-instance                          │
│ Creation Date        │ 2022-12-06 21:41:09 +0000 UTC        │
│ Instance Type        │ standard.micro                       │
│ Template             │ Linux Ubuntu 22.04 LTS 64-bit …
```

Implements v2 Reverse DNS options

---

cmd/instance_create.go
cmd/instance_pool_create.go
cmd/instance_pool_update.go
cmd/instance_reset.go
cmd/instance_template_list.go
cmd/instance_template_show.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/template.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

- sort by name the list of private templates
-  deprecates ` template-filter` in instancepool create|update commands: replaced by `template-visibility`
- Use `FindTemplate` to search template by ID or by Name 
<details>
<summary>Tests</summary>
```
exo c template list  --visibility private
┼──────────────────────────────────────┼────────────────────────────┼────────────────┼───────────────────────────────┼
│                  ID                  │            NAME            │     FAMILY     │         CREATION DATE         │
┼──────────────────────────────────────┼────────────────────────────┼────────────────┼───────────────────────────────┼
│ _____________REDACTED_______________ │ tpl_D                      │ other (64-bit) │ 2021-11-18 12:50:06 +0000 UTC │
│ …
```

Deprecates template-filter, improve search template by name

---

cmd/dbaas_show_opensearch.go

This PR adds proper pointer handling (prevents panic on nil pointer) in `dbaas opensearch` commands.

Don't panic on nil pointer in dbaas opensearch commands

---

cmd/sks_nodepool_show.go

```
│     SKS NODEPOOL     │                                      │
......
│ Version              │ 1.24.8                               │
│ Size                 │ 2                                    │
│ State                │ running                              │
│ Taints               │ n/a                                  │
│ Labels               │ n/a                                  │
│ Add Ons              │ storage-lvm                          │
```

sks nodepool show: add addons

---

cmd/dbaas_migration.go
cmd/dbaas_migration_stop.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/client_mock.go
vendor/github.com/exoscale/egoscale/v2/database_mysql.go
vendor/github.com/exoscale/egoscale/v2/database_pg.go
vendor/github.com/exoscale/egoscale/v2/database_redis.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This PR adds a new command: `exo dbaas migration stop`.
New command will stop migration if it is running.
**Note**: due to internal implementation of Aiven API, time window to stop a migration begins couple of minutes after database creation.

Add command to stop database migration

---

.github/workflows/main.yml
cmd/elastic_ip_show.go
go.mod
go.sum
utils/utils.go
vendor/github.com/exoscale/egoscale/.golangci.yml
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/doc.go
vendor/github.com/exoscale/egoscale/isos.go
vendor/github.com/exoscale/egoscale/templates.go
vendor/github.com/exoscale/egoscale/v2/client.go
vendor/github.com/exoscale/egoscale/v2/deploy_target.go
vendor/github.com/exoscale/egoscale/v2/instance.go
vendor/github.com/exoscale/egoscale/v2/instance_pool.go
vendor/github.com/exoscale/egoscale/v2/oapi/oapi.gen.go
vendor/github.com/exoscale/egoscale/v2/sks_nodepool.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/github.com/exoscale/egoscale/virtual_machines.go
vendor/modules.txt

We show the names of the instances attached to an elastic IP when the user calls `exo c elastic-ip show $SOME_EIP`.

elastic_ip: show names of instances attached to EIP

---

cmd/instance_reveal_password.go
cmd/security_group_list.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/instance.go
vendor/github.com/exoscale/egoscale/v2/security_group.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

New behavior
- `exo compute security-group list --visibility (public|private)`
- `exo compute instance reveal-password ${ID|NAME}`
With guidance from @kobajagi, thanks!

compute: add support for public security groups and password reveal

---

cmd/config.go
cmd/instance.go
cmd/instance_snapshot_create.go

Instance snapshot command had a hardcoded timeout of 60 minutes without a way to extend it. This PR removes the hardcoded value. Default value is now 10 minutes (fairly small for snapshot), however timeout override is applied and can easily extend value (env `EXOSCALE_API_TIMEOUT` or config `clientTimeout`).
**edit:** Default Timeout bumped to 20 minutes. Also added descriptive error when timeout is hit on create snapshot command:
```
$ EXOSCALE_API_TIMEOUT=1 go run . c i snapshot create myinstance
✔ Creating snapshot of instance "myinstance"... 1m0s
error: Request timeout reached. Snapshot creation is not canceled and might still be running, check the status with : exo c i snapshot list
exit status 1
```

Remove hardcoded instance snapshot timeout

---

CHANGELOG.md
cmd/instance_ssh.go

Fix exception when trying to connect to a private instance
```
exo c i ssh  private
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1085e3d]
goroutine 1 [running]:
github.com/exoscale/cli/cmd.(*instanceSSHCmd).cmdRun(0xc000274300, 0xc0008a9ce8?, {0xc0008a9cc0?, 0x0?, 0x0?})
github.com/exoscale/cli/cmd/instance_ssh.go:105 +0x31d
github.com/spf13/cobra.(*Command).execute(0xc00031a280, {0xc00011f2f0, 0x1, 0x1})
github.com/spf13/cobra@v1.3.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x203a180)
github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.3.0/command.go:902
github.com/exoscale/cli/cmd.Execute({0x18a5c20?, …
```

[compute] ssh: no support for private instances

---

cmd/config_add.go

Remove the call to v1 API (`listAccounts` ) when adding new account. We don't have the same functionality in v2 to do a switch, but feature does not provide much value so I decided to remove it. Now it works by always asking user to manually input all account data, which was a failback before in case of a restricted key:
```
$ go run . config                                                                        
✔ <Configure a new account>                                                                                            
[+] API Endpoint [https://api.exoscale.com/v1]:                                                                        
[+] API Key [none]: EXOxxx...
[+] Secret Key [none]: ...
[+] Account name [none]: api …
```

Don't fetch account info when adding new account

---

CHANGELOG.md
cmd/status.go
pkg/status/status.go
pkg/status/status_test.go

With Incidents and maintenances
```
go run  . status
┼─────────────────┼───────────────────────────────────────────────────────────────────────────────────────────┼
│ EXOSCALE STATUS │                                                                                           │
┼─────────────────┼───────────────────────────────────────────────────────────────────────────────────────────┼
│ Services        │   Global     operational                                                                  │
│                 │   CH-GVA-2   operational                                                                  │
│                 │   CH-DK-2    minor                                                                        │
│                 │   DE-FRA-1   minor …
```

status: show new status page

---

CHANGELOG.md
cmd/instance_reset.go

Instance reset was setting the instance base template to account default instead of the current instance template.
Before the fix, if I reset a debian instance with my local settings, it was using ubuntu after reset.
Now it sticks to debian, as expected.
```
❯ go run main.go compute instance reset -z de-fra-1 VM-b4235265-75e5-4c04-8d03-86dc35914c9f
[+] Are you sure you want to reset instance "VM-b4235265-75e5-4c04-8d03-86dc35914c9f"? [yN]: y
✔ Resetting instance "VM-b4235265-75e5-4c04-8d03-86dc35914c9f"... 15s
┼──────────────────────┼─────────────────────────────────────────┼
│   COMPUTE INSTANCE   │                                         │
┼──────────────────────┼─────────────────────────────────────────┼
│ ID                   │ b4235265-75e5-4c04-8d03-86dc35914c9f    │
│ Name …
```

fix: instance reset wrong default template

---

cmd/root.go

If users specify an inexistent configuration file they will get a confusing error message.
panic: can not look up shorthand which is more than one ASCII character: "..."
goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).ShorthandLookup(0xc0008bc400, {0x7ffd5e794c14?, 0x7ffd5e794c14?})
/home/sauterp/src/github.com/exoscale/cli/vendor/github.com/spf13/pflag/flag.go:362 +0x106
github.com/exoscale/cli/cmd.getCmdPosition({0x137389e, 0x6})
/home/sauterp/src/github.com/exoscale/cli/cmd/root.go:380 +0x188
github.com/exoscale/cli/cmd.isNonCredentialCmd(...)
/home/sauterp/src/github.com/exoscale/cli/cmd/root.go:351
github.com/exoscale/cli/cmd.initConfig()
/home/sauterp/src/github.com/exoscale/cli/cmd/root.go:244 +0x1053
github.com/spf13/cobra.(*Command).preRun(...) …

root cmd: fix panic if inexistent config file is given

---

CHANGELOG.md
cmd/nlb_service_update.go

After an update of the mode of a NLB service heathcheck from http to tcp, URI and tslsni were still set
HTTP Healtcheck
```
exo c nlb service show  d03dde14-0436-43e3-8017-0faa958be35a bc2fdb55-0ba8-4f12-a836-b4a9b1cba2f9  -z ch-gva-2
│     NLB SERVICE      │                                      │
│ ID                   │ bc2fdb55-0ba8-4f12-a836-b4a9b1cba2f9 │
│ Name                 │ my-nlb-service                       │
│ Description          │                                      │
│ Instance Pool ID     │ 23bd21b9-f8cb-45e1-bb18-e495f457bfb1 │
│ Protocol             │ tcp                                  │
│ Port                 │ 80 …
```

nlb: remove uri and tlssni from nlb service healthcheck mode is tcp

---

.github/workflows/release.yml
.goreleaser.yml
CHANGELOG.md

We want to verify signatures of released packages before installing them with the install-latest.sh script and in makepkg. For the AUR source package we need a signature that includes the source of the go.mk submodule.
```shell
goreleaser release --skip-docker --skip-publish --skip-announce --skip-validate --clean
• starting release...
• loading config file                              file=.goreleaser.yml
• loading environment variables
• getting and validating git state
• building...                                    commit=7b144e8e5914e2e6cb6c3569bc5821b7cbfe4024 latest tag=v1.72.1
• pipe skipped                                   reason=validation is disabled
• parsing tag
• setting defaults
• DEPRECATED: `archives.rlcp` will be the default soon, check …
```

release: create source tarball and sign all artifacts

---

.github/workflows/release.yml
CHANGELOG.md

We adapted the 'exoscale-cli' and exoscale-cli-bin' packages on AUR to verify GPG signatures before installation. The sha256sums list now contains a 'SKIP' element for the corresponding element in the sources list that references the signature file. We need to adapt the sed line that substitutes the checksum to respect this.
I tested the release script locally on the adapted PKGBUILD files in 'exoscale-cli' and 'exoscale-cli-bin' and was able to build and install the packages.

release: adapt AUR release script for signed packages

---

CHANGELOG.md
cmd/internal/x/x.gen.go

[SC-77650]
Local dev test:
```
(exo3) ~$ exo x list-secondary-volume-snapshots
{
"secondary-volumes": [
{
"created-at": "2023-09-19T14:19:01Z",
"id": "615cfd09-e76a-4bea-9c16-00d552c5ddce",
"labels": {},
"name": "null_20230919141901",
"size": 107374182400,
"state": "created",
"volume-id": "0f173f38-cb86-46bf-8b0f-a2e5aaa9b2da"
}
]
}
(exo3) ~$ exo x create-secondary-volume snapshot-id:615cfd09-e76a-4bea-9c16-00d552c5ddce
{
"id": "3e83c032-9a7e-4a0e-bfe1-4afcaddb8314",
"reference": {
"command": "get-secondary-volume",
"id": "068dd0f2-3465-4586-a0f0-4bb374d74161",
"link": "/v2/secondary-volume/068dd0f2-3465-4586-a0f0-4bb374d74161"
},
"state": "pending"
}
(exo3) ~$ exo x list-secondary-volumes
{
"secondary-volumes": [
{
"blocksize": 4096,
"created-at": …
```

exo x cmds: secondary volume add create from snapshot-id

---

.github/workflows/release.yml
CHANGELOG.md

Both [AUR releases for signed packages](https://github.com/exoscale/cli/actions/runs/6349777603/job/17248953628) failed during the pgp verification:
```shell
==> Verifying source file signatures with gpg...
exoscale-cli_1.74.0.tar.gz ... FAILED (unknown public key 03686F8CDE378D41)
==> ERROR: One or more PGP signatures could not be verified!
```
I wasn't able to reproduce the issue locally with low effort. I'm able to run makepkg in an archlinux container with no issue. I verified that the public key is not present before I run `makepkg` and that it is present afterwards. This means makepkg must contact keyservers in the background to receive the keys. This can fail for a number of reasons, like keyservers not being available, networking or bugs in the gpg version provided by the GH …

aur releases: skip pgp check

---

.github/workflows/release.yml
.gitignore
.goreleaser.yml
CHANGELOG.md

We publish Debian packages to SOS for users to install through the `apt` package manager.
The release workflow completed successfully [on my fork](https://github.com/sauterp/cli/actions/runs/6316082862) and released the package to the bucket `sauterp-exoscale-packages`.
We tested installing the released packages with
```shell
docker run -it ubuntu /bin/bash
apt update && apt install -y gpg ca-certificates
echo "deb [signed-by=/etc/apt/keyrings/exoscale.gpg] https://sos-ch-gva-2.exo.io/sauterp-exoscale-packages/deb/cli stable main" > /etc/apt/sources.list.d/exoscale.list
gpg --keyserver keyserver.ubuntu.com --recv-keys 7100E8BFD6199CE0374CB7F003686F8CDE378D41
gpg --export 7100E8BFD6199CE0374CB7F003686F8CDE378D41 > /etc/apt/keyrings/exoscale.gpg
apt update
apt …
```

release workflow: publish deb packages to SOS

---

CHANGELOG.md
README.md
install-latest.sh

We install the cli as a debian package through apt from the repository on SOS, if the version of apt is >= 2.2.0. With version 2.2.0 keyrings under `/etc/apt/keyrings` became the recommended way to install GPG keys. Distributions who have older versions of apt may still use the legacy keyring. On these older distributions we keep installing the package through dpkg.
The advantage of installing from the SOS repo is that apt will detect new versions when they are released, so users won't have to manually install them anymore.
test on ubuntu
```shell
root@3a631c8cc8ef:/# ./install-latest.sh
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 03686F8CDE378D41: public key …
```

install script: install from SOS apt repo if possible

---

CHANGELOG.md
cmd/dbaas.go

Due to incompatible regex engines for pattern validation, JSON Schema for dbaas settings can throw error when loaded by [gojsonschema](github.com/xeipuuv/gojsonschema). This throws error in CLI and prevents running any commands for the database. Client side validation should be considered opportunistic (as server will validate data as well), this PR disables validation if JSON Schema cannot be loaded. 
Current:
```
$ exo dbaas update mydb --grafana-settings '{"oauth_allow_insecure_email_lookup": false}'
error: invalid settings: unable to validate JSON Schema: pattern must be a valid regex
```
New:
```
$ go run . dbaas update mydb --grafana-settings '{"oauth_allow_insecure_email_lookup": false}'
✔ Updating Database Service "mydb"... 0s
$ go run . dbaas show mydb …
```

dbaas: don't throw error if dbaas settings JSON schema cannot be loaded

---

.github/workflows/main.yml
.github/workflows/release.yml
.goreleaser.yml

We use a script in go.mk as a custom publisher to publish releases to SOS. As with debian releases, we only keep the last 10 versions of the cli available in the bucket.
This PR depends on https://github.com/exoscale/go.mk/pull/38
The publisher ran successfully [on my fork](https://github.com/sauterp/cli/actions/runs/6624841931/job/17994621129)
I tested that the released RPMs can be installed with DNF on Fedora 37 by adding a repo file `/etc/yum.repos.d/sauterp-rpm-test-repo.repo` with the following content:
```
[sauterp-rpm-test-repo]
name=created by dnf config-manager from s3:exoscale-package
baseurl=https://sos-ch-gva-2.exo.io/sauterp-exoscale-packages/rpm/cli
enabled=1
repo_gpgcheck=1
gpgcheck=0
gpgkey=https://keys.openpgp.org/vks/v1/by-fingerprint/7100E8BFD …
```

publish releases as rpm packages on SOS

---

CHANGELOG.md
install-latest.sh

We change the installation script so it can install packages from SOS repos directly trhough yum and dnf.
The script was tested in docker containers for ubuntu:jammy(apt), ubunty:focal(dpkg), fedora(dnf), centos:7(yum). I tested both fresh installs, downgrading and upgrading an existing installation.

install-script: install rpms from SOS repo

---

CHANGELOG.md
README.md

We document how to install the cli on Arch Linux from the AUR.
Commands were tested in a docker container.

README: document installation from AUR

---

CHANGELOG.md
cmd/internal/x/x.gen.go

Use new blockstorage api endpoints. [SC-82348]
Tested with pp gva2:
```
$ exo x list-block-storage-volumes -z ch-gva-2
{
"block-storage-volumes": [
{
"blocksize": 4096,
"created-at": "2023-11-15T18:10:57Z",
"id": "af57c03b-3522-47f3-a7b9-0ccdffac1a7c",
"instance": {
"id": "f9294189-e1d3-47d4-ad77-4c852abf0b58"
},
"labels": {},
"name": "myvolume",
"size": 107374182400,
"state": "attached"
},
{
"blocksize": 4096,
"created-at": "2023-11-16T10:38:02Z",
"id": "3b706780-b6a9-45ba-b154-fa9e739d824b",
"labels": {},
"name": "loadtest-instance-3",
"size": 107374182400,
"state": "detached"
},
....
$ exo x create-block-storage-volume -z ch-gva-2 name:myvol2,size:120
{
"id": "53c216ba-3c42-41c6-ae73-5c379902e6b9",
"reference": {
"command": "get-block-storage-volume",
"id": …
```

exo x : rename secondary volume -> blockstorage volume commands

---

CHANGELOG.md
cmd/internal/x/x.gen.go

OpenAPI generator does not create correct Go code for a body parameter
for a GET method. Use URL query parameter instead.
[SC-82458]
https://github.com/exoscale/entities/pull/703
```
)$ bin/exo -A ppcnautze x -z ch-gva-2 list-block-storage-volumes --instance-id c7ba4419-7731-428a-b7ae-a3d81ed156a7
{
"block-storage-volumes": [
{
"blocksize": 4096,
"created-at": "2023-11-24T10:01:18Z",
"id": "70b8e0f2-527b-4ea6-a49d-3541ea71b246",
"instance": {
"id": "c7ba4419-7731-428a-b7ae-a3d81ed156a7"
},
"labels": {},
"name": "loadtest-instance-16",
"size": 107374182400,
"state": "attached"
}
]
}
```

exo x: list-block-storage-volumes: instance id use query param

---

.goreleaser.yml
CHANGELOG.md
Makefile
completion/main.go

The completion for fish was missing, adding it
After installing the binary with the completions, everything is working as expected, and the completion works :

completion: Adding fish support

---

CHANGELOG.md
cmd/iam.go
cmd/iam_org_policy_update.go
cmd/iam_role_create.go
cmd/iam_role_update.go

Fixes issues with empty description and policy in `iam role create` command.
Also renames `iam org-policy` command `replace` to `update` (to be inline with `role`). `replace` is now alias command so it is backward compatible change.
```bash
$ go run . iam role create api5                                                                                                                                           
┼─────────────┼──────────────────────────────────────┼                                        
│ ID          │ 7df88e66-5986-4b15-b908-8811460c0225 │                                        
│ Name        │ api5                                 │ …
```

iam role create: fix description and policy when not set

---

.github/actions/build/action.yaml
.gitignore
CHANGELOG.md
Makefile

We remove the `go.mk` as a submodule and ensure that it is automatically cloned and kept up to date with make.
If `go.mk` doesn't exist, it will be cloned:
```shell
❯ make build
Cloning into 'go.mk'...
remote: Enumerating objects: 308, done.
remote: Counting objects: 100% (194/194), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 308 (delta 130), reused 135 (delta 91), pack-reused 114
Receiving objects: 100% (308/308), 60.52 KiB | 911.00 KiB/s, done.
Resolving deltas: 100% (173/173), done.
mkdir -p '/home/sauterp/src/github.com/exoscale/cli/bin'
'/home/sauterp/bin/go' build \
\
-ldflags "-X main.commit=5890d142 -X main.branch=philippsauter/sc-88913/go-mk-provide-alternative-to-submodule-approach -X main.buildDate=2024-02-16T13:57:06+0000 -X …
```

go.mk: use as a plain repo instead of a submodule

---

CHANGELOG.md
cmd/limits.go

We don't yet show the limit on block storage volumes in the `exo limits command`.
```shell
./bin/exo limits
┼────────────────────────────┼──────┼─────┼
│          RESOURCE          │ USED │ MAX │
┼────────────────────────────┼──────┼─────┼
│ Elastic IP addresses       │ 0    │ 5   │
│ IAM API keys               │ 41   │ 100 │
│ Compute instance GPUs      │ 0    │ 1   │
│ Private networks           │ 0    │ 32  │
│ Compute instances          │ 2    │ 20  │
│ Compute instance templates │ 0    │ 30  │
│ Network Load Balancers     │ 0    │ 5   │
│ Compute instance snapshots │ 0    │ 30  │
│ SKS clusters               │ 1    │ 3   │
│ SOS buckets                │ 16   │ 100 │
│ Block Storage Volumes      │ 14   │ 20  │
┼────────────────────────────┼──────┼─────┼
```

limits: get block storage volume limit

---

CHANGELOG.md
cmd/x.go

Initially the idea of the `exo x` command was for it to be a last resort only, however since it has been quite stable and is now used by many customers we add the alias `exo api` which is less discouraging.
```shell
$ ./bin/exo api help-input
Input to the CLI is handled via ...
$ ./bin/exo x help-input
Input to the CLI is handled via ...
```

x: make `exo api` an alias to `exo x`

---

README.md

The step is no longer necessary to build from source as the Makefile pulls `go.mk`.

go.mk: remove submodule mention from README

---

CHANGELOG.md
cmd/iam_org_policy_reset.go

Updates `exo iam org-policy reset` confirmation text to remove ambiguity.
```bash
$ go run . iam org-policy reset
[+] This action will reset your Org Policy to the default, removing any constraints that were set in the Org Policy. Proceed? [yN]: y
```

Update iam org-policy reset confirmation text

---

.goreleaser.yml
CHANGELOG.md

This PR removes Windows ARM build targets from goreleaser configuration.
Stats show we have no downloads for those, by removing them we will speed up the build time a bit.
We can revert it if we receive a request for specific builds in the future. 
Not applicable.

Remove Windows ARM targets from prebuilt binaries

---

CHANGELOG.md
cmd/instance_reset_password.go

Remove the wrong instance reset password `rm` alias.

Instance reset password: remove wrong "rm" alias

---

CHANGELOG.md
cmd/sks_create.go

We add the flag `--exoscale-csi` to the `exo compute sks create` command. If set, a cluster with the CSI addon will be created. Unlike the `CCM` and `metrics-server` addons which have to be explicitly disabled with a `--no-...` flag, the CSI addon has to be explicitly enabled because for some users may not need it.
```shell
❯ ./bin/exo compute sks create --exoscale-csi --zone ch-gva-2 --nodepool-size 1 my-csi-test-cluster
❯ ./bin/exo compute sks --zone ch-gva-2 show my-csi-test-cluster
┼───────────────┼──────────────────────────────────────────────────────────────────┼
│  SKS CLUSTER  │                                                                  │
┼───────────────┼──────────────────────────────────────────────────────────────────┼
│ ID            │ …
```

sks: flag for CSI addon

---

CHANGELOG.md
README.md
cmd/client.go
cmd/cmd.go
cmd/config.go
cmd/config_add.go
cmd/root.go
pkg/account/account.go

At config creation with exo cli here is the output:
```Toml
[[accounts]]
account = 'no longer used name foo'
defaultZone = 'ch-gva-2'
key = 'EXOxxx'
name = 'foo'
secret = 'xxx'
``` 
When you switch account with `exo config` here is the reloaded config account foo:
```Toml
[[accounts]]
account = 'no longer used name foo'
clientTimeout = 20
defaultTemplate = 'Linux Ubuntu 22.04 LTS 64-bit'
defaultZone = 'ch-gva-2'
environment = 'api'
key = 'EXOxxx'
name = 'foo'
secret = 'xxx'
```
I agree those config fields can be useful to be set by the user if needed but not auto generated on basic configuration profile.
Here is what I Updated in the change, by default we create the config:
```Bash
✔ <Configure a new account>
[+] API Key [none]: EXOxxx
[+] Secret Key [none]: xxx
[+] Name [none]: foo
``` …

Config: Remove unused field on config reload 

---

CHANGELOG.md
cmd/sks_create.go
cmd/sks_nodepool_add.go
cmd/sks_nodepool_show.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/v2/sks_nodepool.go
vendor/modules.txt

Adds the following flags:
On SKS Cluster creation:
* nodepool-image-gc-low-threshold
* nodepool-image-gc-high-threshold
* nodepool-image-gc-min-age
The equivalent on SKS Nodepool add:
* image-gc-low-threshold
* image-gc-high-threshold
* image-gc-min-age
```
➜  ~/exo/cli git:(tgrondier/sc-66948/cli) go run . compute sks create my-test-cluster \                                                                     
--zone de-muc-1 \
--service-level starter \
--nodepool-name my-test-nodepool \
--nodepool-size 3 \
--nodepool-security-group sks-security-group --nodepool-image-gc-high-threshold 66 --nodepool-image-gc-low-threshold 33 --nodepool-image-gc-min-age "6m"
✔ Creating SKS cluster "my-test-cluster"... 2m3s
✔ Adding Nodepool "my-test-nodepool"... 33s …
```

SKS nodepool: allow specifying kubelet image gc parameters on creation

---

CHANGELOG.md
cmd/client.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/v2/sks_nodepool.go
vendor/github.com/exoscale/egoscale/v3/api.go
vendor/github.com/exoscale/egoscale/v3/operations.go
vendor/github.com/exoscale/egoscale/v3/schemas.go
vendor/modules.txt

```BASH
EXOSCALE_TRACE=true go run main.go c bs get XXXXX
>>> Operation: list-zones
GET /v2/zone HTTP/1.1
Host: api-ch-gva-2.exoscale.com
Authorization: EXO2-HMAC-SHA256 credential=XXXXXXXX
User-Agent: egoscale/0.102.3 (go1.21.3; linux/amd64)
<<< HTTP/2.0 200 OK
Connection: close
Content-Type: application/json; charset=utf-8
Date: Fri, 12 Apr 2024 13:16:59 GMT
Exo-Cm-Hash: XXXXXXX
Referrer-Policy: no-referrer-when-downgrade
Strict-Transport-Security: max-age=31557600; includeSubDomains; preload
X-Content-Type-Options: nosniff always
X-Xss-Protection: 1; mode=block always
{"zones":[{"id":"1128bd56-b4d9-4ac6-a7b9-c715b187ce11","name":"ch-gva-2","api-endpoint":"https://api-ch-gva-2.exoscale.com/v2","sos-endpoint":"https://sos-ch-gva-2.exo.io"},{"id":"91e5e9e4-c9ed-4b76-bee4-427004b3baf9","nam …
```

Egoscale v3: Fix the exoscale trace output

---

CHANGELOG.md
cmd/storage_presign.go

Fixes https://github.com/exoscale/cli/issues/588
Instead of
```shell
> exo storage presign 2dsofijc02q9jd
panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
github.com/exoscale/cli/cmd.init.func65(0x29651a0, {0xc0009466f0, 0x1, 0x16e0fff?})
github.com/exoscale/cli/cmd/storage_presign.go:44 +0x425
github.com/spf13/cobra.(*Command).execute(0x29651a0, {0xc000932480, 0x3, 0x4})
github.com/spf13/cobra@v1.3.0/command.go:856 +0x69d
github.com/spf13/cobra.(*Command).ExecuteC(0x29610a0)
github.com/spf13/cobra@v1.3.0/command.go:974 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.3.0/command.go:902
github.com/exoscale/cli/cmd.Execute({0x1eeae38?, 0x2882900?}, {0x1eeb668?, 0xc0000061c0?}) …
```

storage presign: fix panic when parsing arg[0]

---

CHANGELOG.md
cmd/limits.go

We introduced two new quotas for block storage:
- One for the cumulative size of all block storage volumes of an org
- One for the maximum size of a block storage volume 
Before
```
❯ go run . limits    
┼────────────────────────────┼──────┼──────┼
│          RESOURCE          │ USED │ MAX  │
┼────────────────────────────┼──────┼──────┼
│ Elastic IP addresses       │ 0    │ 10   │
│ IAM API keys               │ 4    │ 100  │
│ Compute instance GPUs      │ 0    │ 1    │
│ Private networks           │ 0    │ 32   │
│ Compute instances          │ 33   │ 50   │
│ Compute instance templates │ 0    │ 30   │
│ Network Load Balancers     │ 0    │ 5    │
│ Compute instance snapshots │ 0    │ 30   │
│ SKS clusters               │ 0    │ 3    │
│ SOS buckets                │ 1    │ 100  │
│ Block …
```

Display the two new blockstorage quotas

---

CHANGELOG.md
cmd/config.go

```shell
❯ exo config add
[+] API Key [none]: asdf
[+] Secret Key [none]: asdf
[+] Name [none]: asdf
✔ at-vie-1
[+] Set [asdf] as default account? [yN]: N
no default account set
```

config: remind user that no default account was set

---

CHANGELOG.md
pkg/output/outputter.go

Fixes panic in `dbaas migration show`.
Bug was in the shared table format code that makes assumption about our API that don't apply to dbaas API (due to originating from Aiven).
Before:
```bash
$ exo dbaas migration status mydb2
panic: reflect: call of reflect.Value.FieldByName on string Value
goroutine 1 [running]:
reflect.flag.mustBe(...)
reflect/value.go:233
reflect.Value.FieldByName({0x14d1fe0?, 0xc0002947c0?, 0x170a2ea?}, {0x16e1b46?, 0x1f12c78?})
reflect/value.go:1361 +0x1c8
github.com/exoscale/cli/pkg/output.Table({0x1594560, 0xc000a9a040})
github.com/exoscale/cli/pkg/output/outputter.go:287 +0xc56
github.com/exoscale/cli/cmd.(*databaseMigrationStatus).ToTable(0xc000d12420?)
github.com/exoscale/cli/cmd/dbaas_migration_status.go:44 +0x1d …
```

Fix panic in dbaas migration show

---

CHANGELOG.md
cmd/sks_update.go

We add the `--enable-csi-addon` flag to the `sks update` command.
egoscale v2 doesn't pass the AddOns field to the API and instead of updating v2 I refactored the update command to use v3.
On a cluster that wasn't created with the CSI Addon:
```shell
> exo c sks update -z ch-gva-2 test-cluster --enable-csi-addon
✔ Updating SKS cluster "test-cluster"... 42s
┼───────────────┼──────────────────────────────────────────────────────────────────┼
│  SKS CLUSTER  │                                                                  │
┼───────────────┼──────────────────────────────────────────────────────────────────┼
│ ID            │ 746f5de4-ee31-4761-a7c6-9fc71f3e9bf4                             │
│ Name          │ test-cluster …
```

sks: enable CSI addon on existing clusters

---

CHANGELOG.md
Makefile
cmd/iam_role_show.go
cmd/iam_role_update.go
cmd/icmp_code.go
cmd/icmp_type.go
cmd/instance_pool_delete.go
cmd/instance_snapshot_create.go
cmd/sks_nodepool_delete.go
cmd/sks_nodepool_evict.go
cmd/sks_nodepool_scale.go
cmd/sks_nodepool_show.go
cmd/sks_nodepool_update.go

```shell
❯ make lint
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 3), reused 6 (delta 2), pack-reused 0
Unpacking objects: 100% (9/9), 5.47 KiB | 2.74 MiB/s, done.
From github.com:exoscale/go.mk
529be42..c320e5b  master     -> origin/master
* [new tag]         v2.0.0     -> v2.0.0
'/home/sauterp/bin/go' install honnef.co/go/tools/cmd/staticcheck@2023.1.7
'/home/sauterp/go/bin/staticcheck' \
\
./...
```

go.mk: lint with staticcheck

---

.goreleaser.yml
CHANGELOG.md
Makefile

Newer goreleaser versions deprecated few directives we use. Most are just renamed now, one become enforced and is not needed. No breaking changes expected.
Requires https://github.com/exoscale/go.mk/pull/43
Before:
```bash
$ goreleaser check                                                                                                                                                        
• checking                                 path=
• DEPRECATED:  source.rlcp  should not be used anymore, check https://goreleaser.com/deprecations#sourcerlcp for more info
• DEPRECATED:  brews.folder  should not be used anymore, check https://goreleaser.com/deprecations#brewsfolder for more info
• DEPRECATED:  brews.tap  should not be used anymore, check …
```

Update deprecated goreleaser directives

---

CHANGELOG.md
cmd/instance_pool_show.go
cmd/instance_show.go

Renames keys that did not match actual data:
- `template_id` -> `template`;
- `zoneid` -> `zone`.
These were present in both `c instance show` and `c instance-pool show` commands.
```bash
$ go run . c i show 1d1b482c-adcf-4928-acd9-fdffbe2d7c98 --output-format json | jq                                                                                        
{                                                                                                                                                                                            
"id": "1d1b482c-adcf-4928-acd9-fdffbe2d7c98",                                                                                                                                              
"name": "my-instance", …
```

Fix instance/ipool key naming in json output

---

CHANGELOG.md
cmd/sks_nodepool_show.go

```shell
❯ ./bin/exo -A exosauterp compute sks nodepool show abc def -z ch-gva-2
┼─────────────────────────┼──────────────────────────────────────┼
│      SKS NODEPOOL       │                                      │
┼─────────────────────────┼──────────────────────────────────────┼
│ Instance Type           │ standard.medium                      │
┼─────────────────────────┼──────────────────────────────────────┼
```

sks nodepool: show instance family

---

CHANGELOG.md
pkg/output/outputter.go

Previously we were using `html/template` which would result in strings being rendered as escaped html
Before:
```
➜ exo dbaas show test --output-template '{{.Kafka.ConnectionInfo.AccessCert}}'                                                  24-07-04 16:08 
-----BEGIN CERTIFICATE-----
MIIEVzCCAr&#43;gAwIBAgIUCoWog7/IGKm3ts&#43;xO6kSfkk/UHwwDQYJKoZIhvcNAQEM
...
```
W/ this PR:
```
➜ go run . dbaas show test --output-template '{{.Kafka.ConnectionInfo.AccessCert}}'                                                                                        24-07-04 16:57 
-----BEGIN CERTIFICATE-----
MIIEVzCCAr+gAwIBAgIUCoWog7/IGKm3ts+xO6kSfkk/UHwwDQYJKoZIhvcNAQEM
```

output template: use text/template

---

CHANGELOG.md
cmd/instance_delete.go
cmd/output.go

Compute Instance delete, remove multiple entities by their IDs/Names
Deleting a list of instance
```BASH
go run main.go c i delete test1 test2 test3
[+] Are you sure you want to delete instance "test1"? [yN]: y
[+] Are you sure you want to delete instance "test2"? [yN]: y
[+] Are you sure you want to delete instance "test3"? [yN]: y
✔ Deleting instance "test1, test2, test3"... 9s
```
Not existing instance in list
```
go run main.go c i delete test1 test2 test404 test3
[+] Are you sure you want to delete instance "test1"? [yN]: y
[+] Are you sure you want to delete instance "test2"? [yN]: y
error: "test404" not found in ListInstancesResponse: resource not found
exit status 1
```
Force deletion like rm cmd even if not exist
```
go run main.go c i delete test1 …
```

Compute Instance delete: Remove multiple entities by their IDs/Names

---

CHANGELOG.md
cmd/dbaas_show_mysql.go
cmd/dbaas_show_opensearch.go
cmd/dbaas_show_pg.go
cmd/dbaas_show_redis.go

This PR rebuilds the connection URI by fetching password from a dedicated database service endpoint (for services that support credentials in URI).

dbaas: use dedicated reveal-password endpoint to fetch password and build URI

---

CHANGELOG.md
cmd/root.go

Fixes bug with  EXOSCALE_API_TIMEOUT being ignored when credentials are specified in ENV.
Before change:
```bash
$ EXOSCALE_API_KEY=xxx EXOSCALE_API_SECRET=xxx EXOSCALE_API_TIMEOUT=1 exo c i snapshot create myinstance -z ch-gva-2
✔ Creating snapshot of instance "myinstance"... 3m18s
┼───────────────┼────────────────────────────────────────┼
│   SNAPSHOT    │                                        │
┼───────────────┼────────────────────────────────────────┼
│ ID            │ b41413b9-58bc-4ccf-a498-7391bb603b91   │
│ Name          │ myinstance_ROOT-7380078_20240805161855 │
│ Creation Date │ 2024-08-05 16:18:55 +0000 UTC          │
│ State         │ exported                               │
│ Size (GB)     │ 50                                     │
│ Instance …
```

Set API timeout from ENV when credentials are specified in ENV

---

.github/workflows/release.yml
CHANGELOG.md

For archlinux builds install `base-devel` metapackage instead of individual tools. This fixes the build error triggered by missing `debugedit` tool:
```
==> ERROR: Cannot find the debugedit binary required for including source files in debug packages.
```
`base-devel` metapackage contains following packages (as the time of writing):
```
$ pacman -Qi base-devel | grep Depends
Depends On      : archlinux-keyring  autoconf  automake  binutils  bison  debugedit  fakeroot  file  findutils  flex  gawk  gcc  gettext  grep  groff  gzip  libtool  m4  make  pacman  patch  pkgconf  sed  sudo  texinfo  which
```

Fix list of dependencies for archlinux builds

---

.gitignore
.idea/.gitignore
CHANGELOG.md
cmd/instance_create.go
cmd/instance_update.go

added add/remove a protection flag to exo compute, however it did not work as expected
I tested the cli after the changes locally but the protection flag does not work.
```bash
❯ ./exo compute instance update --help
This command updates an Instance .
Supported output template annotations: .ID, .Name, .CreationDate, .InstanceType, .Template, .Zone, .AntiAffinityGroups, .DeployTarget, .SecurityGroups, .PrivateInstance, .PrivateNetworks, .ElasticIPs, .IPAddress, .IPv6Address, .SSHKey, .DiskSize, .State, .Labels, .ReverseDNS
Usage:
exo compute instance update NAME|ID [flags]
Flags:
-c, --cloud-init string      instance cloud-init user data configuration file path
--cloud-init-compress    compress instance cloud-init user data
-h, --help                   help for …
```

instance: add a protection flag to exo compute

---

CHANGELOG.md
cmd/blockstorage_create.go
cmd/blockstorage_snapshot_create.go
cmd/blockstorage_snapshot_update.go
cmd/blockstorage_update.go

After doing mutations on blockstorage related entities, we do a list to display the change. However this listing was done on the default zone and not on the zone where the update occurred. And because public API only return blockstorage results that live in the same zone, this was causing issues 
Before (default zone is ch-gva-2)
```
❯ exo compute block create test-create -z at-vie-1 --size 100
✔ Creating block storage volume "test-create"... 3s
error: "test-create" not found in ListBlockStorageVolumesResponse: resource not found
```
(The volume was successfully created bu failed to be displayed) 
After
```
❯ go run . compute block create test-create -z at-vie-1 --size 100                 
✔ Creating block storage volume "test-create"... 3s …
```

Pass the zone when listing result of blockstorage operations

---

CHANGELOG.md
cmd/storage_delete.go
pkg/storage/sos/object.go
pkg/storage/sos/object_test.go

Batch objects delete API method from `aws-sdk-go-v2` will not return error as second argument if individual objects failed to be deleted. Instead it will return both list of deleted objects and list of errors in result structure.
This prints errors (if any) after the list of successfully deleted files.

storage: handle errors in batch objects delete action

---

install-latest.sh

The installation fails right now if `uname -m` reports `aarch64` which, according to wikipedia, is a synonym for `arm64` architecture (https://en.wikipedia.org/wiki/AArch64).
Therefore, this PR adds a rule for renaming `aarch64` to `arm64` in the installation script.
Using `debian:stable-slim` Docker image on M1 chip reported `aarch64` as the architecture which is how I ran into this issue in the first place. This change made the installation work and running `exo` worked.

Fix installation script to support `aarch64`

---

cmd/ssh_key_list.go

Update ssh-keys list to egoscale v3
```
root@65df3c390733:/cli# go run . compute ssh-key list
┼──────────────────────┼─────────────────────────────────────────────────┼
│         NAME         │                   FINGERPRINT                   │
┼──────────────────────┼─────────────────────────────────────────────────┼
│ key1                 │ 5d:49:0a:8a:f2:17:9f:ef:9e:06:e0:46:ad:42:ef:91 │
│ key2                 │ 19:59:d8:58:ce:be:4c:8b:fa:5b:c2:3c:0b:27:a1:12 │
│ key3                 │ 93:d5:1a:55:36:ba:e9:6b:16:b8:17:9a:39:a4:31:1a │
│ key4                 │ 7e:08:64:f5:95:bb:b9:69:37:1d:ab:4e:3c:cc:19:43 │
│ key5                 │ 1c:d8:19:38:a3:c4:bf:87:f8:78:80:c4:71:46:c6:34 │
│ key6                 │ ea:ab:c5:7f:dc:44:31:b9:6a:ad:21:19:7c:7b:3e:0c │
│ …
```

refactor(ssh-keys-list): Update ssh-keys list to egoscale v3

---

go.mod
vendor/modules.txt

`replace` directives prevent usage of `go install` or `go run` against this package.
Furthermore, the `replace` directive had a typo in it, so it was not doing anything anyway.
Removed replace directive.
Ran `go mod tidy`
Ran `go mod vendor`
Checked that no dependencies were changed
Ran `go test ./...` for good measure

fix: Remove ineffective replace directive

---

docs/404.html
docs/404.md
docs/main.go

This brings support for using the markdown files in our community pages. The new code assumes the doc renderer will be hugo: this removes quite a bit of complexity.
Users who just want markdown can use this code as an inspiration.

feat(doc): Update program to generate markdown docs for the CLI

---

CHANGELOG.md
cmd/instance_update.go

Fix zone context on Instance protection flag

Instance: Fix instance protection flag update zone context

---

CHANGELOG.md
cmd/iam_api_key_create.go
cmd/iam_api_key_delete.go
cmd/iam_api_key_list.go

Update IAM API Key manipulation to egoscale v3
Tested locally :
```
root@c863e81f354a:/exo# go run . iam api-key create test-create-key test-temp-mlec
┼────────┼─────────────────────────────────────────────┼
│ Name   │ test-create-key                             │
│ Key    │ EXO...                                      │
│ Secret │ [REDACTED]                                  │
│ Role   │ 6fa23920-433c-4048-89b5-e3075f23336f        │
┼────────┼─────────────────────────────────────────────┼
root@c863e81f354a:/exo# go run . iam api-key list
┼──────────────────────────────────────┼─────────────────────────────┼─────────────────────────────────────────────────────────────────────────────┼
│                 NAME                 │             KEY             │ …
```

refactor(iam-api-key): Update IAM API Key manipulation to egoscale v3

---

CHANGELOG.md
cmd/anti_affinity_group_show.go
cmd/iam_api_key_create.go

Fix a bug in the "show" command to list all attached instances from different zones, while the user tries to printanti-affinity group, the attached instance list is printed empty.
```
PS C:\Users\Administrator\Desktop\Apps\Exoscale\CLI\exo-cli show anti-affinity-group with instances> go run .  compute instance create se-test-2 --anti-affinity-group=se-test-1 --zone=de-muc-1
✔ Creating instance "se-test-2"... 12s
│ ID                   │ 583ee938-e5f8-4142-a3f4-f08dc77ce3a9 │
│ Name                 │ se-test-2                            │
│ Creation Date        │ 2024-11-07 …
```

anti-affinity group: fix a bug in the "show" command to list all attached instances from different zones

---

.github/workflows/release.yml

Triggers a rebuild of the community docs when we release a new CLI version.
`GH_TOKEN` was set the value in the secret.
```console
$ export GH_TOKEN=<redacted>
$ gh workflow run gen-cli.yaml -R exoscale/community-ng -f version=master
✓ Created workflow_dispatch event for gen-cli.yaml at main
To see runs for this workflow, try: gh run list --workflow=gen-cli.yaml
```

feat(ci): Trigger regeneration of community docs on release

---

CHANGELOG.md
cmd/instance_update.go

If we fail to create the client, this will result in a SIGSEV when using it

instance update: fixing no err check after creating client

---

CHANGELOG.md
pkg/storage/sos/object.go

The user can now use a recursive flag to download files with tree directories, different use cases were considered as well:
- The user can specify a directory with the `-r` flag and the directory with its sub-directory will be downloaded and its content.
- if the sub-directory contains duplicated files it will skip the duplicated files and download the rest.
- if the user specifies destination folder not ending "/", it will check if it's a file, otherwise it throws an error, if not it will create the file
- if the user tries to download a file that already exists it will throw an error.
```
PS C:\Users\Administrator\Desktop\Apps\Exoscale\CLI\exo-cli show anti-affinity-group with instances> exo storage list sos://test-99/      
DIR  sub-1/
DIR  sub-2/
PS …
```

storage: Adding recursive feature to the storage command.

---

CHANGELOG.md
utils/utils.go

`exo compute security-group show` iterates through all zones to retrieve instances associated with it. If a single API endpoint happened to throw an error, the call itself would error out. This fix allows showing that security group while still showing an error
```
➜  ~/exo/cli git:(tgrondier/sc-114869/exo-c-sh-show-error-in-preprod) ✗ go run . c sg show edc0d129-2f94-4531-920e-7cf798439cd3                                                                                             25-01-06 16:40 
error while listing instances in security group: 1 error occurred:
* Get "https://ppapi-at-vie-2.exoscale.com/v2/instance": dial tcp: lookup ppapi-at-vie-2.exoscale.com on 127.0.0.53:53: server misbehaving
┼──────────────────┼──────────────────────────────────────────── …
```

security-group show: fix empty response if an API endpoint is misbehaving

---

CHANGELOG.md
cmd/dbaas_database.go
cmd/dbaas_database_create.go
cmd/dbaas_database_create_mysql.go
cmd/dbaas_database_create_pg.go
cmd/dbaas_database_delete.go
cmd/dbaas_database_delete_mysql.go
cmd/dbaas_database_delete_pg.go
cmd/dbaas_show_mysql.go
cmd/dbaas_show_pg.go
cmd/dbaas_user_create_kafka.go
cmd/dbaas_user_create_mysql.go
cmd/dbaas_user_create_opensearch.go
cmd/dbaas_user_create_pg.go
cmd/dbaas_user_delete_kafka.go
cmd/dbaas_user_delete_opensearch.go

Allows users to use the CLI to directly automate database creation for selected services
Also includes a few check before creating users for DBAAS service to verify if the service is ready to accept user creation
```
➜  ~/exo/cli git:(tgrondier/sc-114061/dbaas-support-for-mysql-posgres-database) go run . dbaas create pg hobbyist-2 test-pg                                                                                                                                                                                 25-01-09 12:18 
✔ Creating Database Service "test-pg"... 0s
┼───────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼
│   DATABASE SERVICE    │ …
```

dbaas: database management for mysql, pg

---

.github/workflows/golangci-lint.yml
CHANGELOG.md
go.mod

We add a golangci-lint action. It shouldn't be considered blocking, it may detect bugs. staticcheck is still our main linter.

lint: add golangci-lint action

---

CHANGELOG.md
cmd/storage_download.go
pkg/storage/sos/object.go

This PR fixes a bug in file rename for `storage download` command. Bug was introduced in 1.83.0.
To make it easier to grasp the code for file downloads I refactored it to be explicit on supported download patterns.
One file download, no rename:
```
$ ./cli storage download predrag-test-bucket/website/prepare.sh
website/prepare… [==============================================================================] 155.00 b / 155.00 b | 0s
$ ls prepare.sh 
prepare.sh
```
Same file download, no rename, no force flag
```
$ ./cli storage download predrag-test-bucket/website/prepare.sh
error: failed to download single file: file "prepare.sh" already exists, use flag `-f` to overwrite
```
One file download, no rename, force flag
```
$ ./cli storage download …
```

Refactor sos.DownloadFiles & fix file rename

---

CHANGELOG.md
pkg/storage/sos/object.go

uploading bigfiles hangs, if there are no permissions, instead of throwing.
[Ticket](https://app.shortcut.com/exoscale/story/117395/gh-issue-cli-bug-upload-of-big-objects-to-bucket-stuck)
testing:
```
dd if=/dev/zero of=smallfile bs=1M count=1
dd if=/dev/zero of=bigfile bs=10M count=1
```
**bigfile  HANGS, UNTIL CTRL+C**
```
go run main.go storage upload bigfile sos://buckettest
bigfile          [======================================>---------------------------------------] 5.00 MiB / 10.00 MiB | 1s
^Cerror: operation error S3: CreateMultipartUpload, https response error StatusCode: 403, RequestID: b88e8a41-9db1-414e-bff1-cbfe2d6803ca, HostID: b88e8a41-9db1-414e-bff1-cbfe2d6803ca, api error AccessDenied: You are not authorized to perform put-object on bucket buckettest
exit status 1
``` …

fixing bigfile upload stuck issue.

---

CHANGELOG.md
pkg/output/outputter.go

Removes default HTML escaping for json output.
```
➜  ~/exo/cli git:(tgrondier/sc-121173/cli-iam-utf8-parsing) exo iam role get --policy 93ecd283-84f2-4b58-9e1c-ede702de2826                                                                                                  25-05-12 11:58 
┼─────────┼────────────────────────────────┼─────────────┼─────────────────────────────────────────────────────────────────────────────┼
│ SERVICE │ TYPE (DEFAULT STRATEGY "DENY") │ RULE ACTION │                               RULE EXPRESSION                               │
┼─────────┼────────────────────────────────┼─────────────┼─────────────────────────────────────────────────────────────────────────────┼
│ sos     │ rules                          │ allow       │ (operation in …
```

JSON output: do not escape HTML

---

CHANGELOG.md
cmd/dns.go
cmd/dns_add.go
cmd/dns_create.go
cmd/dns_delete.go
cmd/dns_list.go
cmd/dns_records_update.go
cmd/dns_remove.go
cmd/dns_show.go

```
➜  ~/exo/cli git:(tgrondier/feat/dns-egoscale-v3) ✗ go run . dns create foo.bar                                                                                                                                             25-05-12 14:36 
✔ Creating DNS domain "foo.bar"... 3s
Domain "foo.bar" was created successfully
➜  ~/exo/cli git:(tgrondier/feat/dns-egoscale-v3) ✗ go run . dns ls                                                                                                                                                         25-05-12 14:36 
┼──────────────────────────────────────┼─────────┼
│                  ID                  │  NAME   │
┼──────────────────────────────────────┼─────────┼
│ 89083a5c-b648-474a-0000-00000013966a │ foo.bar │ …
```

dns: move to egoscale v3

---

CHANGELOG.md
cmd/sks_create.go
cmd/sks_show.go
cmd/sks_update.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/v3/operations.go
vendor/modules.txt

Allows updating the list of feature gates for an SKS cluster
```
➜  ~/exo/cli git:(tgrondier/sc-121631/terraform-provider-cli-expose-feature-gates) go run . compute sks update kube-proxy-default -z ch-gva-2 --feature-gates GracefulNodeShutdown                                                                                                                           25-05-07 9:53 
✔ Updating SKS cluster "kube-proxy-default"... 42s
┼───────────────────┼──────────────────────────────────────────────────────────────────┼
│    SKS CLUSTER    │                                                                  │
┼───────────────────┼──────────────────────────────────────────────────────────────────┼
│ ID                │ cea1041c-ce7e-4624-9856-67ae9e4bfac7 …
```

SKS cluster: feature-gates support

---

CHANGELOG.md
cmd/compute/security_group/security_group.go
cmd/compute/security_group/security_group_create.go
cmd/compute/security_group/security_group_delete.go
cmd/compute/security_group/security_group_list.go
cmd/compute/security_group/security_group_rule.go
cmd/compute/security_group/security_group_rule_add.go
cmd/compute/security_group/security_group_rule_delete.go
cmd/compute/security_group/security_group_show.go
cmd/compute/security_group/security_group_source.go
cmd/compute/security_group/security_group_source_add.go
cmd/compute/security_group/security_group_source_remove.go
cmd/instance_list.go
cmd/subcommands/init.go

Refactoring CLI folder structure:
Moving SecurityGroups to the corresponding subfolder
```
o run main.go compute security-group create new-sg
✔ Creating Security Group "new-sg"... 3s
┼──────────────────┼──────────────────────────────────────┼
│  SECURITY GROUP  │                                      │
┼──────────────────┼──────────────────────────────────────┼
│ ID               │ 76f49f1a-3ae5-4966-b523-02040fe2996c │
│ Name             │ new-sg                               │
│ Description      │                                      │
│ Ingress Rules    │ -                                    │
│ Egress Rules     │ -                                    │
│ External Sources │ -                                    │
│ Instances        │ - …
```

Cmd subfolders: SecurityGroup

---

CHANGELOG.md
cmd/blockstorage_snapshot_update.go
cmd/blockstorage_update.go
cmd/cmd.go
cmd/compute/instance_pool/instance_pool.go
cmd/compute/instance_pool/instance_pool_create.go
cmd/compute/instance_pool/instance_pool_delete.go
cmd/compute/instance_pool/instance_pool_evict.go
cmd/compute/instance_pool/instance_pool_list.go
cmd/compute/instance_pool/instance_pool_scale.go
cmd/compute/instance_pool/instance_pool_show.go
cmd/compute/instance_pool/instance_pool_update.go
cmd/config.go
cmd/instance_create.go
cmd/instance_reset.go
cmd/instance_template_show.go
cmd/subcommands/init.go

Refactoring CLI folder structure:
Moving InstancePools to the corresponding subfolder
```
go run main.go compute instance-pool create testme -t a3955d41-4012-44ea-b442-7e22bad598f8
✔ Creating Instance Pool "testme"... 21s
│    INSTANCE POOL     │                                      │
│ ID                   │ 9f996822-de4f-47e5-b0b9-801bcef02d5c │
│ Name                 │ testme                               │
│ Description          │                                      │
│ Instance Type        │ standard.medium                      │
│ Template             │ Linux Fedora CoreOS 41 64-bit        │
│ Zone                 │ ch-gva-2 …
```

Cmd subfolders: InstancePool

---

CHANGELOG.md
cmd/compute/instance_template/instance_template.go
cmd/compute/instance_template/instance_template_delete.go
cmd/compute/instance_template/instance_template_list.go
cmd/compute/instance_template/instance_template_register.go
cmd/compute/instance_template/instance_template_show.go
cmd/subcommands/init.go

Refactoring CLI folder structure:
Moving instance template related commands to the corresponding subfolder
```
go run main.go compute instance-template list
┼──────────────────────────────────────┼─────────────────────────────────────────────────────┼─────────────────────────┼───────────────────────────────┼
│                  ID                  │                        NAME                         │         FAMILY          │         CREATION DATE         │
┼──────────────────────────────────────┼─────────────────────────────────────────────────────┼─────────────────────────┼───────────────────────────────┼
│ 1299c3d9-d484-44cb-9f85-cfaf6ffc890c │ VMware SD-WAN 3.3.2 BYOL                            │ vmware sd-wan           │ 2020-10-16 07:19:04 +0000 UTC │
│ …
```

Cmd subfolders: Instance template

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/exoscale/egoscale/v3/operations.go
vendor/github.com/exoscale/egoscale/v3/schemas.go
vendor/github.com/exoscale/egoscale/v3/version.go
vendor/modules.txt

Fixes a bug introduced in #684 by bumping egoscale
On master:
```
➜  ~/exo/cli git:(master) go run . compute eip show 9237ef31-854f-4143-b015-5eb714a76f72                                                                                                                                                                                                                     25-05-28 8:52 
┼──────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┼
│        ELASTIC IP        │                                                                                  │
┼──────────────────────────┼──────────────────────────────────────────────────────────────────────────────────┼
│ ID                       │ …
```

eip show shows incorrect instance info

---

CHANGELOG.md
go.mod
go.sum
utils/utils.go
vendor/github.com/exoscale/egoscale/v2/oapi/oapi.gen.go
vendor/modules.txt

Updating `github.com/exoscale/egoscale` dep as well as adding support for the new `hr-zag-1` in the list of default zones for egoscale v2.
Before:
```
$ EXOSCALE_TRACE=1 exo c i list 2>&1 | grep hr-zag-1
```
Now:
```
$ EXOSCALE_TRACE=1 go run . c i list 2>&1 | grep hr-zag-1
Host: api-hr-zag-1.exoscale.com
```

utils: Add hr-zag-1 in the list of zones (egoscale v2)

---

CHANGELOG.md
cmd/compute/sks/sks_nodepool_update.go

Fixes the bug with incorrect empty map initialization.
Before:
```sh
$ go run . c sks nodepool update 2929386e-6f35-494e-82f1-e7d73bbff227 c816545d-5252-4b3c-a324-6ac4834bd7d3 --taint dedicated=special-user:NoSchedule                      
panic: assignment to entry in nil map                                                                                                                                                        
goroutine 1 [running]:                                                                                                                                                                       
github.com/exoscale/cli/cmd/compute/sks.(*sksNodepoolUpdateCmd).CmdRun(0xc000389d40, 0xc000954008, {0xc0003db4c0?, 0xd22fa0?, 0xc000053c90?}) …
```

Fix panic in sks nodepool update

---

CHANGELOG.md
cmd/compute/elastic_ip/elastic_ip_create.go

Corrects the EIPv6 parameter when creating elastic IP (regression [here](https://github.com/exoscale/cli/commit/46509a77c88694c1fc6a00e9042f9a24dde84cb2)).
Before:
```bash
$ exo version
exo 1.85.4 23cf25de (egoscale 0.102.3)
$ exo c eip create --ipv6
error: CreateElasticIP: http response: Bad Request: Invalid value `:inetv6` at 'addressfamily' (description: `Elastic IP address family`): should be one of :inet4, :inet6
```
Now:
```bash
$ go run . c eip create --ipv6
✔ Creating Elastic IP... 3s
┼────────────────┼──────────────────────────────────────┼
│   ELASTIC IP   │                                      │
┼────────────────┼──────────────────────────────────────┼
│ ID             │ a6272372-10f8-4f53-888e-e5cf2832de6e │
│ IP Address     │ …
```

Fix EIPv6 address family

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/exoscale/egoscale/v3/client.go
vendor/github.com/exoscale/egoscale/v3/operations.go
vendor/github.com/exoscale/egoscale/v3/version.go
vendor/modules.txt

Bumps egoscale client to include [retryable HTTP client](https://github.com/exoscale/egoscale/pull/710).

Bump egoscale v3.1.25 (retryable HTTP client)
