README.md
cmd/affinitygroup.go
cmd/privnet.go
cmd/privnet_create.go
cmd/privnet_list.go
cmd/privnet_test.go
cmd/request.go
go.mod
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/Gopkg.lock
vendor/github.com/exoscale/egoscale/networks.go
vendor/github.com/exoscale/egoscale/request.go
vendor/github.com/exoscale/egoscale/security_groups.go
vendor/github.com/exoscale/egoscale/version.go
vendor/github.com/exoscale/egoscale/virtual_machines.go
vendor/modules.txt

Until the exo command it removed from egoscale, this has to be done once in a while.
@mcorbin did I miss anything?

dep: backport from egoscale v0.11.6

---

.golangci.yml
.gometalinter.json
Jenkinsfile
cmd/privnet.go
cmd/template.go
cmd/vm_create.go
doc/main.go

gometalinter being too slow and playing badly with go1.11.

jenkins: use golangci

---

.travis.yml

(we need the token in the travis builds anyway)

travis: push hugo website to gh-pages

---

cmd/vm_create.go

and the jumbo service offering.

vm: add missing paren

---

cmd/privnet_show.go

privnet: backport changes from egoscale

---

.dockerignore
.gitignore
.goreleaser.yml
Dockerfile
Makefile
README.md

goreleaser don't like CGO_ENABLED=1
to be tested...

docker: build image that runs in a docker env.

---

cmd/root.go

Run version cmd when config file is missing

---

cmd/config_show.go
cmd/sos_list.go

Add `-R`, `--raw` on `exo sos ls` raw display of listing
Fix #29

Exo sos ls - add raw listing

---

cmd/config.go
cmd/config_set.go

Add account selection:
Able to select one
then quit or add another account

Add interactive account selection

---

cmd/sos_download.go

```
$ exo sos download eip config.go testtest.go
config.go  100 % [==============================================================] 0s
Successfully downloaded config.go into "testtest.go"
```

Add sos download progress bar

---

.goreleaser.yml
CHANGELOG.md
cmd/root.go
cmd/status.go

Fix https://github.com/exoscale/cli/issues/35

Exo status

---

cmd/template.go

**Now**
``` console
% exo vm serviceoffering list
% exo template list
```
**Then**
```console
% exo vm serviceoffering list
% exo vm template list
```

template: move under vm

---

.travis.yml
Makefile

Do not force docker builds by default and provide an expected environment.
I would like to see travis.yml make use of the Makefile
Linting fails for me at the moment, I will look into it.

Makefile: adapt to local development

---

CHANGELOG.md
cmd/privnet.go
cmd/privnet_associate.go
cmd/privnet_create.go
cmd/privnet_list.go
cmd/privnet_show.go
cmd/privnet_test.go
cmd/privnet_update.go

Fix https://github.com/exoscale/cli/issues/41

Add cidrMask on privnet

---

cmd/snapshot.go
cmd/snapshot_create.go
cmd/snapshot_delete.go
cmd/snapshot_list.go
cmd/snapshot_revert.go
cmd/vm_list.go
go.mod
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/snapshots.go
vendor/github.com/exoscale/egoscale/version.go
vendor/modules.txt

`exo snapshot`
`exo snapshot create vmTest`
`exo snapshot delete rt_ROOT-690946_20181108115920`
`exo snapshot ls`
`exo snapshot ls rt`
`exo snapshot ls vm1 vm2 vm3`
`exo snapshot revert fbda5929-9752-443c-a2d2-386ec2ab3403 `

Add Snapshot support

---

cmd/firewall.go

firewall: fix bug in getMyCIDR() function

---

cmd/dns_delete.go
cmd/dns_remove.go

(#46) DNS remove confirmation

---

cmd/sos_upload.go

List recursively folder and subfolder:
```
$ go run main.go sos upload -r bucket-test ./github.com/exoscale/cli/cmd
0s 100 % [==============================================================] affinitygroup.go
0s 100 % [==============================================================] affinitygroup_create.go
0s 100 % [==============================================================] affinitygroup_delete.go
0s 100 % [==============================================================] affinitygroup_list.go
0s 100 % [==============================================================] api.go
0s 100 % [==============================================================] api_layout.go
0s 100 % [==============================================================] config.go
0s 100 % …
```

Add recursivity on sos upload

---

cmd/kube_create.go
cmd/kube_list.go
go.mod
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/client.go
vendor/github.com/exoscale/egoscale/virtual_machines.go
vendor/modules.txt

```console
% exo lab kube list
```
> GET /compute?apikey=EXOc94bc655ff901b7218a5c3cd&command=listVirtualMachines&expires=2018-12-07T09%3A22%3A07%2B0100&page=1&pagesize=50&response=json&signature=****&signatureversion=3&tags%5B0%5D.key=managedby&tags%5B0%5D.value=exokube
also, I've refactored that four _if_ deep function.

vendor: bump egoscale to experimental version

---

cmd/api.go
cmd/api_layout.go
go.mod
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/admin/README.md
vendor/github.com/exoscale/egoscale/admin/doc.go
vendor/github.com/exoscale/egoscale/admin/virtual_machines.go
vendor/github.com/exoscale/egoscale/runstatus.go
vendor/github.com/exoscale/egoscale/runstatus_event.go
vendor/github.com/exoscale/egoscale/runstatus_incident.go
vendor/github.com/exoscale/egoscale/runstatus_maintenance.go
vendor/github.com/exoscale/egoscale/runstatus_service.go
vendor/github.com/exoscale/egoscale/version.go
vendor/modules.txt

```console
% exo api vm listVirtualMachines --listall=true
unknown flag: --listall
% EXOSCALE_TRACE= exo api vm listAll --listall=true                                                                         
2018/11/27 10:28:43 GET /compute?apikey=EXOc94bc655ff901b7218a5c3cd&command=listVirtualMachines&expires=2018-11-27T10%3A38%3A43%2B0100&listall=true&response=json&signature=...&signatureversion=3 HTTP/1.1
Host: api.exoscale.ch
User-Agent: exoscale/egoscale (0.13.0-alpha.0)
2018/11/27 10:28:43 HTTP/2.0 200 OK
Content-Type: application/json;charset=utf-8
Date: Tue, 27 Nov 2018 09:28:42 GMT
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Accept-Encoding, User-Agent
X-Content-Type-Options: nosniff
X-Request-Id: 3784bda5d6e6e342a3b59633c0664254
X-Xss-Protection: 1; …
```

api: admin listVMs

---

cmd/firewall_add.go

the previous refactoring broke it.

firewall: fix ping6 protocol name

---

LICENSE
README.md
main.go

the way I managed the license was a bit bodged.

readme: send some kudos

---

.golangci.yml
.travis.yml
cmd/dns_records_update.go
cmd/firewall.go
cmd/firewall_remove.go
cmd/firewall_show.go
cmd/root.go

travis: add scopelint

---

cmd/template_list.go

Added:
```
$ exo vm template list --help
Usage:
exo vm template list [keyword] [flags]
Aliases:
list, ls
Flags:
-h, --help   help for list
-i, --iso    List ISOs
```
```
$ exo vm template list --iso
```
```
┼───────┼─────────┼──────────┼─────────────┼
│ NAME  │  SIZE   │   ZONE   │     ID      │
┼───────┼─────────┼──────────┼─────────────┼
│ ISO-0 │ 1.0 MiB │ ch-dk-2  │ XXXXXXXXX-0 │
│ ISO-1 │ 4.0 GiB │ ch-gva-2 │ XXXXXXXXX-1 │
│ ISO-2 │ 1.0 MiB │ ch-gva-2 │ XXXXXXXXX-2 │
│ ISO-3 │ 1.0 MiB │ de-fra-1 │ XXXXXXXXX-3 │
│ ISO-4 │ 4.0 GiB │ ch-dk-2  │ XXXXXXXXX-4 │
│ ISO-5 │ 1.0 MiB │ at-vie-1 │ XXXXXXXXX-5 │
┼───────┼─────────┼──────────┼─────────────┼
```
Signed-off-by: Pierre-Emmanuel Jacquier <pierre-emmanuel.jacquier@epitech.eu>

Add list iso on exo vm template list

---

cmd/kube_create.go
cmd/vm_create.go

This to change it to a joke from It's Always Sunny in Philadelphia.
It would be a fun little joke for people to see.
Signed-off-by: JJ Asghar <jja@ibm.com>

What do now?

---

cmd/firewall_add.go

8 and 128 are defined elsewhere already

firewall: remove magic numbers

---

cmd/eip_delete.go

closes #100 
closes #99 
ping @ste-m 
```
% exo eip delete 159.100.241.220 359f1254-1199-4c66-a559-88354d555f42 159.100.241.192
[+] sure you want to delete "38b1448c-eb22-42f0-8ca3-deeb33c255bd" EIP [yN]: y
[+] sure you want to delete "359f1254-1199-4c66-a559-88354d555f42" EIP [yN]: y
[+] sure you want to delete "f4ca70bf-e1c4-416e-bd69-8290e2b46fe6" EIP [yN]: n
Remove "38b1448c-eb22-42f0-8ca3-deeb33c255bd" EIP ⠼                                                                                done!
Remove "359f1254-1199-4c66-a559-88354d555f42" EIP ⠼                                                                                done!
```

eip: pimp delete up

---

.gitignore
.goreleaser.yml
Makefile

to be tested on a macOS.
```
% man exo                                                                                                             
exo(1)                                                                                                                              exo(1)
NAME
exo - Manage your Exoscale infrastructure easily
% exo api vm
addNic                  expunge                 reboot                  scale                   updateVMAffinityGroup                        
changeService           getPassword             recover                 start                   updateVMNicIP                                
deleteReverseDNSFromVM  getUserData             removeNic               stop                                                                 
deploy …
```

goreleaser: put the bash_completion into brew

---

.gitignore
.goreleaser.yml
Makefile

make: don't gunzip the manpages

---

README.md

:metal:
Signed-off-by: JJ Asghar <jja@ibm.com>

Found a misspelling.

---

.travis.yml
cmd/config.go
cmd/config_show.go
cmd/root.go
cmd/sos_acl.go

Fix panic with env credentials

---

.travis.yml
README.md

the website is gone... :sheep:

website: bump hugo

---

README.md
website/layouts/_default/baseof.html
website/layouts/_default/single.html
website/layouts/index.html
website/layouts/partials/footer.html
website/layouts/partials/summary.html

Bulma update

---

CHANGELOG.md
cmd/affinitygroup_list.go
cmd/affinitygroup_show.go

```
% exo affinitygroup list
```
|         NAME         |                   DESCRIPTION                    | SIZE |                  ID                  |
|----------------------|--------------------------------------------------|------|--------------------------------------|
| docker-swarm-manager | keep the swarm managers on different hypervisors | 0    | 7e446f5a-3987-43fc-a81c-d999bf125996 |
| default              | default anti-affinity group                      | 0    | 6d7bc27c-6c8d-4b6a-ae97-83f73df18667 |
```
% exo affinitygroup show default
Affinity Group:  default
ID:              6d7bc27c-6c8d-4b6a-ae97-83f73df18667
Description:     default anti-affinity group
Type:            host anti-affinity
VirtualMachines: n/a
```

affinitygroup: enrich show and list

---

cmd/kube_create.go

lab: kube: add flag --version to create subcommand

---

Makefile

makefile: build exoscale/cli:latest

---

cmd/affinitygroup_delete.go
cmd/eip_associate.go
cmd/eip_dissociate.go
cmd/firewall_delete.go
cmd/privnet_delete.go
cmd/privnet_dissociate.go
cmd/sshkey_delete.go

Fix #99
make like #101 
before:
```
$ exo eip dissociate 0.0.0.0 vm-test
0xc000026810
```
after:
add async task with spiner and specific message
```
$ exo eip dissociate 0.0.0.0 vm-test
[+] sure you want to dissociate "0.0.0.0" EIP from "vm-test" [yN]: y
dissociate "bd65fd1c-4c60-45f2-a384-f4d9b7827ff5" EIP ⠏                                         done!
```

Pimp CMDs having this issue (issue #99) (pr #101)

---

cmd/template_delete.go
go.mod
vendor/github.com/exoscale/egoscale/templates.go
vendor/github.com/exoscale/egoscale/version.go
vendor/modules.txt

```
./exo -A prod vm template delete 52d6c0b0-a2a6-4513-a962-fb4f354fd7d8 26cc59ad-3cb7-4fe8-a2b6-946ec5bae97d
[+] Are you sure you want to delete template: "52d6c0b0-a2a6-4513-a962-fb4f354fd7d8" [yN]: y
[+] Are you sure you want to delete template: "26cc59ad-3cb7-4fe8-a2b6-946ec5bae97d" [yN]: y
delete template "52d6c0b0-a2a6-4513-a962-fb4f354fd7d8" ⠼                                 done!
delete template "26cc59ad-3cb7-4fe8-a2b6-946ec5bae97d" ⠼                                done!
```

templates: add the "exo vm template delete" subcommand

---

cmd/template_register.go
go.mod
vendor/github.com/exoscale/egoscale/templates.go
vendor/github.com/exoscale/egoscale/version.go
vendor/modules.txt

Custom templates should not be featured.

template register: remove the featured flag

---

cmd/privnet_delete.go

before:
```
exo privnet delete bbb aaa
[+] sure you want to delete "bbb" private network [yN]: y
[+] sure you want to delete "bbb" private network [yN]: y
```
now:
```
[+] sure you want to delete "bbb" private network [yN]: y
[+] sure you want to delete "aaa" private network [yN]: y
```

privnet delete: fix the network name

---

CHANGELOG.md
cmd/root.go
go.mod
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/async_jobs.go
vendor/github.com/exoscale/egoscale/client.go
vendor/github.com/exoscale/egoscale/dns.go
vendor/github.com/exoscale/egoscale/request.go
vendor/github.com/exoscale/egoscale/runstatus.go
vendor/github.com/exoscale/egoscale/version.go
vendor/modules.txt

This change augments the egoscale HTTP client User-Agent value with CLI version/commit information.

Set a custom User-Agent

---

cmd/vm_reboot.go
cmd/vm_reset.go
cmd/vm_resize.go
cmd/vm_scale.go
cmd/vm_start.go
cmd/vm_stop.go

Fix #120
Use asyncTasks() to execute start stop operation

Make vm stop, start... more async

---

cmd/root.go

root: default to $HOME if $XDG_CONFIG_HOME is not set

---

cmd/iam_apikey_operations.go
cmd/iam_apikey_show.go

This PR add the command list Operations for an API key.
Usage:
```
./exo lab iam apikey operations -h
This command lists all suported Operations for an API key.
Supported output template annotations: .Compute, .DNS, .IAM, .SOS
Usage:
exo lab iam apikey operations [filter ...] [flags]
Flags:
-h, --help   help for operations
Global Flags:
-C, --config string            Specify an alternate config file [env EXOSCALE_CONFIG]
-O, --output-format string     Output format (table|json|text)
--output-template string   Template to use if output format is "text"
-Q, --quiet                    Quiet mode (disable non-essential command output
-A, --use-account string       Account to use in config file [env EXOSCALE_ACCOUNT]
```
List operations with filter:
```
./exo lab iam apikey operations "iam" …
```

add list API key Operations

---

cmd/config.go
cmd/config_add.go
cmd/root.go

Change the API endpoint `/compute` to `/v1`

Add API v1 support

---

cmd/template_list.go
cmd/template_register.go

This PR add the `-z` shorthand flag when we have  --zone flag

add -z flag

---

cmd/sos.go

This PR changes the MaxRetry request from minio (default 10) to 2

change minio maxRetry 

---

website/prepare.sh

This way the documentation stays in sync with the code.

Use vendorized source to generate documentation

---

cmd/zone.go

```
exo zone
┼──────────────────────────────────────┼──────────┼
│                  ID                  │   NAME   │
┼──────────────────────────────────────┼──────────┼
│ b0fcd72f-47ad-4779-a64f-fe4de007ec72 │ at-vie-1 │
│ a4f2d4d1-0583-425e-9945-e6d891524093 │ bg-sof-1 │
│ 381d0a95-ed4a-4ad9-b41c-b97073c1a433 │ ch-dk-2  │
│ 1747ef5e-5451-41fd-9f1a-58913bae9702 │ ch-gva-2 │
│ de88c980-78f6-467c-a431-71bcc88e437f │ de-fra-1 │
│ 84e0eb97-bf03-4ed7-999f-96897f08778b │ de-muc-1 │
┼──────────────────────────────────────┼──────────┼
```

sort zone list command

---

cmd/scp.go

This change introduces a new `exo scp` command, similar to `exo ssh`
but for sending/retrieve files to/from a Compute instance.

Add "scp" command

---

cmd/template_register.go
cmd/template_show.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/templates.go
vendor/github.com/exoscale/egoscale/version.go
vendor/modules.txt

Register:
```
$ exo vm template register --name "my-ubuntu-custom-template" --description "test" --url "https://<url>.qcow2" --checksum "6cff454cda4d4845d5bb34398366a5fc" --username ubuntu
Registering the template......................................... success
```
Show:
```
$ exo vm template show my-ubuntu-custom-template --template-filter mine
┼───────────────┼──────────────────────────────────────┼
│   TEMPLATE    │                                      │
┼───────────────┼──────────────────────────────────────┼
│ ID            │ 50081abd-87c0-4872-b357-6cb4c08d9db8 │
│ Name          │ my-ubuntu-custom-template                                │
│ OS Type       │ Other (64-bit)                       │
│ Creation Date │ 2020-07-06T14:11:10+0200             │
│ Zone          │ ch-gva-2 …
```

Add support for compute instance template

---

cmd/api_layout.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/instance_pool.go
vendor/github.com/exoscale/egoscale/version.go
vendor/modules.txt

Add evictInstancePoolMembers to `exo api` command

Add evictInstancePoolMembers to exo api command

---

cmd/template.go

This change improves the behavior of the Compute template selection
logic by picking the most recent result from a list of multiple matching
templates instead of simply returning an error.

Improve Compute template lookup logic

---

cmd/eip_show.go
cmd/internal/x/x.gen.go
cmd/nlb_service_add.go
cmd/nlb_service_show.go
cmd/nlb_service_update.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/internal/v2/v2.gen.go
vendor/github.com/exoscale/egoscale/loadbalancer.go
vendor/github.com/exoscale/egoscale/version.go
vendor/modules.txt

This change adds support for Network Load Balancer service HTTPS health
checking:
```console
$ go run main.go nlb create test-https
┼───────────────────────┼──────────────────────────────────────┼
│ NETWORK LOAD BALANCER │                                      │
┼───────────────────────┼──────────────────────────────────────┼
│ ID                    │ 7c3e13c7-76d8-4baf-bf61-3fa5a165fc0c │
│ Name                  │ test-https                           │
│ Zone                  │ ch-gva-2                             │
│ IP Address            │ 194.182.162.1                        │
│ Description           │                                      │
│ Services              │ n/a                                  │
│ State                 │ running                              │ …
```

nlb: add support for HTTPS service health checking

---

cmd/sos_acl.go
vendor/modules.txt

This change adds support for recursive ACL addition in a bucket.
Example:
```console
$ go run main.go sos show marc-test-ch-gva-2 x
┼─────────┼──────────────────────────────────────────────────┼
│ ACL     │   private                                        │
│         │                                                  │
│ Headers │       KEY                  VALUE                 │
│         │   content-type   text/plain; charset=utf-8       │
│         │   content-type   text/plain; charset=utf-8       │
│         │                                                  │
│ URL     │ https://sos-ch-gva-2.exo.io/marc-test-ch-gva-2/x │
┼─────────┼──────────────────────────────────────────────────┼
$ go run main.go sos show marc-test-ch-gva-2 public/a …
```

sos: support recursive ACL addition

---

cmd/sos_list.go

sos list: display objects without waiting

---

cmd/coi.go

This change introduces a new `exo lab coi` command, to deploy
Container-Optimized Instances.

lab: add "coi" command

---

cmd/instance_pool_create.go
cmd/instance_pool_show.go

This change adds support for Anti-Affinity Groups to Instance Pools.

instancepool: add support for Anti-Affinity Groups

---

cmd/sks_create.go
cmd/sks_show.go
cmd/sks_upgrade.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/internal/v2/sks_cluster.go
vendor/github.com/exoscale/egoscale/internal/v2/sks_nodepool.go
vendor/github.com/exoscale/egoscale/internal/v2/v2.gen.go
vendor/github.com/exoscale/egoscale/loadbalancer.go
vendor/github.com/exoscale/egoscale/sks.go
vendor/github.com/exoscale/egoscale/v2.go
vendor/github.com/exoscale/egoscale/version.go
vendor/modules.txt

* `exo sks`: new `upgrade` command
* `exo sks create`: new flags `--service-level` and `--no-cni`

Update SKS-related commands

---

cmd/instance_pool_delete.go

This change improves the `exo instancepool delete` command by checking
if the specified Instance Pools is not currently referenced by a NLB
service before attempting to delete it.

instancepool: prevent deletion if still referenced

---

cmd/sks_list.go
cmd/sks_nodepool_list.go
cmd/sks_show.go

This change introduces a new `exo sks nodepool list` command.

sks: nodepool: add "list" command

---

cmd/client.go
cmd/sks_nodepool_update.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/anti_affinity_group.go
vendor/github.com/exoscale/egoscale/v2/api/middleware.go
vendor/github.com/exoscale/egoscale/v2/client.go
vendor/github.com/exoscale/egoscale/v2/instance_pool.go
vendor/github.com/exoscale/egoscale/v2/internal/public-api/public-api.gen.go
vendor/github.com/exoscale/egoscale/v2/internal/public-api/public-api.go
vendor/github.com/exoscale/egoscale/v2/network_load_balancer.go
vendor/github.com/exoscale/egoscale/v2/private_network.go
vendor/github.com/exoscale/egoscale/v2/security_group.go
vendor/github.com/exoscale/egoscale/v2/sks.go
vendor/github.com/exoscale/egoscale/v2/test.go
vendor/github.com/exoscale/egoscale/v2/v2.go
vendor/github.com/exoscale/egoscale/version.go
vendor/modules.txt

This change adds support for SKS Nodepool Security Groups and
Anti-Affinity Groups updating.

SKS: support Nodepools SG/AAG updating 

---

cmd/sks_create.go

This changes modifies the `exo sks create` command to use the latest
available version by default, instead of hardcoding it.

sks: create: use the latest version by default

---

cmd/vm.go

This change compresses the cloud-init userdata configuration with gzip
before base64-encoding it.
Fixes #329

vm: compress cloud-init userdata

---

cmd/storage_download.go
cmd/storage_upload.go

This change fixes a bug in the `exo storage download/upload` commands
where user-induced interrupt signal (e.g. `<CTRL + C>`) would not
interrupt in-flight file download/upload.

storage: honor context cancelation in put/get

---

cmd/limits.go

This change adds missing resource limits to the `exo limits` output.

Add missing organization resource limits

---

cmd/firewall.go
cmd/storage_upload.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/security_groups.go
vendor/github.com/exoscale/egoscale/v2/security_group.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

* storage: detect content type before file upload
* firewall: support ICMP SG rules with code/type -1

Various bug fixes

---

cmd/instance.go
cmd/instance_create.go
cmd/instance_list.go
cmd/instance_reboot.go
cmd/instance_scp.go
cmd/instance_security_group.go
cmd/instance_security_group_add.go
cmd/instance_security_group_remove.go
cmd/instance_show.go
cmd/instance_ssh.go
cmd/instance_start.go
cmd/instance_stop.go
cmd/instance_update.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/instance.go
vendor/github.com/exoscale/egoscale/v2/internal/public-api/public-api.gen.go
vendor/github.com/exoscale/egoscale/v2/private_network.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

* compute: instance: add `reboot` command
* compute: instance: add `security-group` commands

New "exo compute instance" commands.

---

cmd/instance_private_network.go
cmd/instance_private_network_add.go
cmd/instance_private_network_remove.go
cmd/instance_private_network_updateip.go
cmd/internal/x/x.gen.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/private_network.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This change adds new `exo compute instance private-network *` commands.

compute: instance: add "private-network" commands

---

cmd/db_service_create.go
cmd/db_service_update.go
cmd/instance_create.go
cmd/instance_pool_create.go
cmd/instance_template.go
cmd/instance_template_delete.go
cmd/instance_template_list.go
cmd/instance_template_register.go
cmd/instance_template_show.go
cmd/instance_type_list.go
cmd/instance_type_show.go
cmd/sks_create.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/.gitmodules
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/Makefile
vendor/github.com/exoscale/egoscale/v2/database.go
vendor/github.com/exoscale/egoscale/v2/internal/public-api/public-api.gen.go
vendor/github.com/exoscale/egoscale/v2/internal/public-api/sks_nodepool.go
vendor/github.com/exoscale/egoscale/v2/sks.go
vendor/github.com/exoscale/egoscale/v2/template.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This change adds new `exo compute instance-template *` commands.

compute: add "instance-template" commands

---

cmd/sks_create.go

This change adds a new `--nodepool-private-network` flag to the
`exo sks create` command

sks: create: add --nodepool-private-network flag

---

cmd/instance_create.go

This change fixes a bug in the `exo compute instance create` command,
where the Private Networks specified wouldn't be attached to the
instance created.

compute: create: fix private networks attachment

---

cmd/deploy_target.go
cmd/instance_reset.go
cmd/instance_resizedisk.go
cmd/instance_scale.go
cmd/ssh_key.go
cmd/ssh_key_list.go
cmd/ssh_key_register.go
cmd/ssh_key_show.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/instance.go
vendor/github.com/exoscale/egoscale/v2/internal/public-api/public-api.gen.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This change adds new `exo compute instance` commands:
* `reset`
* `resize-disk`
* `scale`

compute: instance: add new commands

---

cmd/db_service_create.go
cmd/deploy_target_show.go
cmd/instance_show.go
cmd/instance_snapshot.go
cmd/instance_snapshot_create.go
cmd/instance_snapshot_delete.go
cmd/instance_snapshot_list.go
cmd/instance_snapshot_show.go
cmd/nlb_show.go

This change adds new `exo compute instance snapshot *` commands.

compute: instance: add "snapshot" commands

---

cmd/instance.go
cmd/instance_private_network_updateip.go

This change fixes a bug in the `exo compute instance private-network
update-ip` command.

Fix "exo compute instance private-network update-ip" command

---

cmd/output.go

Fixes #438 #437
```
$ go run . compute instance create my-test-instance
✔ Creating instance "my-test-instance"... 12s
│ ID                   │ 0b102825-38fe-4b24-a342-b7fee1a01720 │
│ Name                 │ my-test-instance                     │
│ Creation Date        │ 2022-03-08 11:17:27 +0000 UTC        │
│ Instance Type        │ standard.medium                      │
│ Template             │ Linux Ubuntu 18.04 LTS 64-bit        │
│ Zone                 │ ch-gva-2                             │
│ Anti-Affinity Groups │ n/a                                  │
│ Security Groups      │ default …
```

cmd.outputTable: Fix panic when single item nested slice is not a struct

---

Makefile
cmd/internal/x/x.gen.go

Regenerating `exo x` to add missing commands.
Improving Makefile so `make x-cmd` is enough to update `x` commands from openapi.

exo x: bump commands (+improve make x-cmd)

---

CHANGELOG.md
cmd/sks_nodepool_add.go

This adds handling addon flags indentically to what we do for clusters.

Add nodepool flag for linbit

---

cmd/dbaas_create_mysql.go
cmd/dbaas_create_pg.go
cmd/dbaas_create_redis.go
cmd/dbaas_update_mysql.go
cmd/dbaas_update_pg.go
cmd/dbaas_update_redis.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/.golangci.yml
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/anti_affinity_group.go
vendor/github.com/exoscale/egoscale/v2/api/security.go
vendor/github.com/exoscale/egoscale/v2/elastic_ip.go
vendor/github.com/exoscale/egoscale/v2/instance.go
vendor/github.com/exoscale/egoscale/v2/instance_pool.go
vendor/github.com/exoscale/egoscale/v2/network_load_balancer.go
vendor/github.com/exoscale/egoscale/v2/network_load_balancer_service.go
vendor/github.com/exoscale/egoscale/v2/oapi/oapi.gen.go
vendor/github.com/exoscale/egoscale/v2/oapi/reference.go
vendor/github.com/exoscale/egoscale/v2/private_network.go
vendor/github.com/exoscale/egoscale/v2/security_group.go
vendor/github.com/exoscale/egoscale/v2/security_group_rule.go
vendor/github.com/exoscale/egoscale/v2/sks_cluster.go
vendor/github.com/exoscale/egoscale/v2/sks_nodepool.go
vendor/github.com/exoscale/egoscale/v2/snapshot.go
vendor/github.com/exoscale/egoscale/v2/template.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This PR updates egoscale dependency and fixes cli to work with generated oapi code.
New egoscale version fixes the bug with request signature of URL paths with unsafe characters.

Update egoscale to fix request signature bug

---

cmd/dbaas_show_pg.go
cmd/instance_template_register.go
cmd/instance_template_show.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/Makefile
vendor/github.com/exoscale/egoscale/go.mod
vendor/github.com/exoscale/egoscale/v2/oapi/.gitignore
vendor/github.com/exoscale/egoscale/v2/oapi/oapi.gen.go
vendor/github.com/exoscale/egoscale/v2/template.go
vendor/modules.txt

This PR adds `build`, `version` and `maintainer` metadata to compute template commands.

Predrag/sc 48552/cli egoscale v2 add support for build version

---

cmd/config.go

This PR updates default instance template to align with Portal.

Update default instance template

---

cmd/internal/x/x.gen.go

This PR updates auto-generated `exo x` commands. No other changes.

Update generated commands (exo x)

---

cmd/internal/x/x.gen.go
cmd/sks_nodepool_add.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/oapi/oapi.gen.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

- SKS nodepool: rename `linbit` addon to `storage-lvm`
- bump egoscale
- regenerate exo x
```
$ go run .  c sks nodepool  add  -z ch-gva-2 my-test-cluster test-storage-lvm --storage-lvm --disk-size 100
✔ Adding Nodepool "test-storage-lvm"... 6s
│     SKS NODEPOOL     │                                      │
│ ID                   │ xxxx-xxxx-xxxxx │
│ Name                 │ test-storage-lvm                     │
│ Description          │                                      │
│ Creation Date        │ 2023-01-05 16:48:09 +0000 UTC        │
│ Instance Pool ID     │ xxxx-xxxx-xxxxx │
│ Instance Prefix      │ pool                                 │
│ Instance Type …
```

SKS nodepool: add storage-lvm addon

---

cmd/internal/x/x.gen.go

Updates auto-generated client (`exo x`) to include Grafana DBAAS commands.

Update `exo x`

---

cmd/instance_list.go
cmd/instance_snapshot_list.go

We fix two data races on maps used for caching in the `compute instance list` and `compute instance snapshot list` commands.

compute instance list commands: fix data races

---

cmd/zone.go

Many commands can operate on all zones we updated list to include "at-vie-2".

zones: add at-vie-2 to the list of zones

---

.gitignore
cmd/dbaas_create.go
cmd/dbaas_create_grafana.go
cmd/dbaas_show.go
cmd/dbaas_show_grafana.go
cmd/dbaas_type_show.go
cmd/dbaas_update.go
cmd/dbaas_update_grafana.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/CHANGELOG.md
vendor/github.com/exoscale/egoscale/v2/oapi/oapi.gen.go
vendor/github.com/exoscale/egoscale/version/version.go
vendor/modules.txt

This PR adds a new database type: grafana.
```
exo dbaas type show grafana
┼────────────────────┼─────────────────────────────┼
│ Name               │ grafana                     │
│ Description        │ Grafana - Metrics Dashboard │
│ Available Versions │                             │
│ Default Version    │ -                           │
┼────────────────────┼─────────────────────────────┼
```

Add dbaas: grafana

---

cmd/storage_upload.go
pkg/storage/sos/acl.go
pkg/storage/sos/acl_test.go
pkg/storage/sos/bucket.go
pkg/storage/sos/bucket_test.go
pkg/storage/sos/client.go
pkg/storage/sos/cors.go
pkg/storage/sos/cors_test.go
pkg/storage/sos/headers.go
pkg/storage/sos/headers_test.go
pkg/storage/sos/metadata.go
pkg/storage/sos/metadata_test.go
pkg/storage/sos/object.go
pkg/storage/sos/object_test.go
pkg/storage/sos/s3api.go
pkg/storage/sos/s3api_mock_test.go

We created unit tests for most of the exported functions in the storage package.

storage: unit tests

---

cmd/instance_show.go

```
│ ID                   │ xxxxxxxxxxxxxxx │
│ Name                 │ test-deploytarget                     │
│ Creation Date        │ 2022-10-29 10:42:11 +0000 UTC        │
│ Instance Type        │ standard.large                       │
│ Zone                 │ de-fra-1                             │
│ Anti-Affinity Groups │ aag-group          │
│ Deploy Target        │ dedicated                            │
...
```
```
│   COMPUTE INSTANCE   │ …
```

Instance: show deploy target

---

README.md

Adds new section in README.md and links GitHub action created by @nhedger.
Replaces #499

Add external contributions section in README.md

---

cmd/dbaas.go

Fixes the issue with validation error for grafana settings `smtp.from_address`. It was identified as a regex pattern originating from Aiven that does not match in Go. Because of this we cannot rely on the clients side validation of patterns and I've chosen to disable the feature and rely on server side validation.
```
$ go run . dbaas update mydb --grafana-settings '{"smtp_server":{"host":"example.net","port":587,"username":"person@example.net","password":"mypassword","from_address":"dashboard@example.net"}}'                                      
✔ Updating Database Service "mydb"... 0s                                                                                    
```

Ignore regex checks in `validateDatabaseServiceSettings`

---

.goreleaser.yml

Update MacOS compiled unified binary name to be inline with others

---

CHANGELOG.md
cmd/config.go

Fixes issue with adding new config.
```
$ go run . config add
[+] API Key [none]: xxxxx
[+] Secret Key [none]: xxxxx
[+] Account name [none]: test
[+] Name [none]: test
✔ at-vie-2
[+] Set [bar] as default account? [yN]: N
```

Fix bug with config add command

---

CHANGELOG.md
cmd/internal/x/x.gen.go

This refreshes `exo x` commands to include the support of the secondary volumes.
```
❯ ./cli x
Low-level Exoscale API calls -- don't use this unless you have to.
These commands are automatically generated using openapi-cli-generator[1],
input parameters can be supplied either via stdin or using Shorthands[2].
[1]: https://github.com/exoscale/openapi-cli-generator
[2]: https://github.com/exoscale/openapi-cli-generator/tree/master/shorthand
Usage:
exo x [command]
Available Commands:
add-external-source-to-security-group         Add an external source as a member of a Security Group
add-instance-protection                       Set instance destruction protection
add-rule-to-security-group                    Create a Security Group rule …
```

exo x : add secondary volume commands

---

CHANGELOG.md
install-latest.sh

If GPG is available, the install-latest.sh script will import the Exoscale tooling key and verify the signatures of downloaded packages, before installing them.
We considered adding user interaction before adding the key, but that makes the script very complex as the script still needs to work in non-interactive shells.
In an Ubuntu container without GPG:
```shell
root@6157e582bafc:/# curl -fsSL https://raw.githubusercontent.com/exoscale/cli/d68b9c06a5512234d9ffb85eb8236ec6424b7581/install-latest.sh | sh
Installing exo CLI, using dpkg
Selecting previously unselected package exoscale-cli.
(Reading database ... 4981 files and directories currently installed.)
Preparing to unpack .../exoscale-cli_1.73.0_linux_amd64.deb ...
Unpacking exoscale-cli (1.73.0) ...
Setting up exoscale-cli (1.73.0) …
```

install script: verify signatures before installation

---

CHANGELOG.md
cmd/iam_role.go
cmd/iam_role_create.go
cmd/iam_role_delete.go
cmd/iam_role_list.go
cmd/iam_role_replace_policy.go
cmd/iam_role_show.go
cmd/iam_role_update.go
go.mod

This PR adds IAM Role management commands:
- `exo iam role list`
- `exo iam role show`
- `exo iam role create` 
- `exo iam delete`
- `exo iam role update`
####List roles
```console
]$ go run . iam role list
┼──────────────────────────────────────┼──────┼──────────┼
│                  ID                  │ NAME │ EDITABLE │
┼──────────────────────────────────────┼──────┼──────────┼
│ df7c20de-5c98-4875-aebc-86bf4303c177 │ api  │ true     │
│ 889cbd68-e91b-46a6-9724-84d8c415bbc7 │ api2 │ true     │
┼──────────────────────────────────────┼──────┼──────────┼
```
```console
$ go run . iam role show api2 
┼─────────────┼──────────────────────────────────────┼
│ ID          │ 889cbd68-e91b-46a6-9724-84d8c415bbc7 │
│ Name        │ api2                                 │ …
```

Add iam role commands

---

CHANGELOG.md
cmd/iam_role_create.go

IAM: fix role create pro tip

---

README.md

Updates README.md with MacOS install instructions

Update README.md with MacOS install instructions

---

CHANGELOG.md
cmd/blockstorage_show.go

```
$ exo compute block-storage show test
┼─────────────────────────┼──────────────────────────────────────┼
│  BLOCK STORAGE VOLUME   │                                      │
┼─────────────────────────┼──────────────────────────────────────┼
│ Block Storage Snapshots │ a24132b7-300f-45b4-8912-f66bbd80231b │
│                         │ 6a3ece44-0932-4bb2-b298-9c5944cbfce8 │
│ Blocksize               │ 4096                                 │
│ Created AT              │ 2024-04-12 15:25:48 +0000 UTC        │
│ ID                      │ a8602290-2df5-4313-9c7f-30d66d8d293f │
│ Instance                │ n/a                                  │
│ Name                    │ test                                 │
│ Size                    │ 10 GiB                               │
│ State …
```

Block Storage: Fix volume show with snapshot

---

.github/workflows/govulncheck.yml
go.mod

Run govulncheck in PRs

---

cmd/internal/x/x.gen.go

This commit updates 'exo x' auto-generated commands. Due to issue with using regex patern validators, following chage was applied to OpenAPI spec before commands were generated:
```
5526d5525
<                         "pattern" : "[^\\s\\/]+",
```

Update exo x (exo api)

---

CHANGELOG.md
cmd/internal/x/x.gen.go

Updates `exo x` commands to include grafana-user-password.

Update exo x

---

cmd/limits.go

To match the better wording of https://github.com/exoscale/console/pull/1611

Reword quota description for blockstorage quotas

---

CHANGELOG.md
Makefile

go.mk: update to v2.0.2

---

CHANGELOG.md
cmd/internal/x/x.gen.go

`exo api` bump for enabling usage of the new DBaaS external endpoints and integrations feature.
See: https://github.com/exoscale/dbaas-api/pull/286
[Draft External Integrations Guide](https://github.com/exoscale/dbaas-api/blob/master/doc/integrations/external_integrations_guide.md)

dbaas: x/api new commands

---

CHANGELOG.md
cmd/internal/x/x.gen.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/v3/operations.go
vendor/github.com/exoscale/egoscale/v3/schemas.go
vendor/modules.txt

Adding commands to manage datadog integration settings.
https://github.com/exoscale/dbaas-api/pull/297

dbaas: datadog integration settings

---

cmd/zone.go

Update zone list to Egoscale v3
```
root@65df3c390733:/cli# go run . zone list
┼──────────┼
│   NAME   │
┼──────────┼
│ at-vie-1 │
│ at-vie-2 │
│ bg-sof-1 │
│ ch-dk-2  │
│ ch-gva-2 │
│ de-fra-1 │
│ de-muc-1 │
┼──────────┼
```

refactor(zones): Update zone list to egoscale v3

---

CHANGELOG.md

Prepare release 1.82.0

---

cmd/instance_snapshot_create.go

fix(error): Improve error message on snapshot creation

---

CHANGELOG.md
cmd/sks_update.go

Confirmed working by colleague

sks update: fix missing feature gate entry

---

CHANGELOG.md
cmd/dbaas_migration_stop.go
cmd/dns_add.go
cmd/dns_delete.go
cmd/dns_records_update.go
cmd/dns_remove.go
cmd/iam.go
cmd/iam_org_policy_reset.go
cmd/iam_org_policy_show.go
cmd/iam_org_policy_update.go
cmd/iam_role_create.go
cmd/iam_role_delete.go
cmd/iam_role_list.go
cmd/iam_role_show.go
cmd/iam_role_update.go
go
go.mod

Move all remaining IAM commands to use exclusively egoscale v3
Testing logs in individual commit messages

IAM org policy and roles: move to egoscale v3

---

CHANGELOG.md
cmd/instance_create.go
cmd/instance_elastic_ip_attach.go
cmd/instance_elastic_ip_detach.go
cmd/instance_enable_tpm.go
cmd/instance_private_network_attach.go
cmd/instance_private_network_detach.go
cmd/instance_private_network_updateip.go
cmd/instance_reboot.go
cmd/instance_reset.go
cmd/instance_resizedisk.go
cmd/instance_scale.go
cmd/instance_security_group_add.go
cmd/instance_security_group_remove.go
cmd/instance_show.go
cmd/instance_snapshot_revert.go
cmd/instance_start.go
cmd/instance_stop.go
cmd/instance_update.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/v3/schemas.go
vendor/modules.txt

- enable instance tpm cmd
- `tpm`, `secureboot` flags on instance creation
```
go run main.go compute instance create testtpms555
✔ Creating instance "testtpms555"... 12s
│ ID                   │ 1801c97d-4622-4c30-aed5-99359af0193c │
│ Name                 │ testtpms555                          │
│ Creation Date        │ 2025-05-19 11:54:48 +0000 UTC        │
│ Instance Type        │ standard.medium                      │
│ Template             │ Linux Ubuntu 22.04 LTS 64-bit        │
│ Zone                 │ ch-gva-2                             │
│ Anti-Affinity Groups │ …
```

tpm and secureboot support.

---

CHANGELOG.md
cmd/nlb_create.go
cmd/nlb_delete.go
cmd/nlb_list.go
cmd/nlb_service_add.go
cmd/nlb_service_delete.go
cmd/nlb_service_show.go
cmd/nlb_service_update.go
cmd/nlb_show.go
cmd/nlb_update.go

Move load-balancer commands to use exclusively egoscale v3
In individual commit messages

load-balancer: move to egoscale v3

---

cmd/dbaas_create_kafka.go
cmd/dbaas_create_mysql.go
cmd/dbaas_create_opensearch.go
cmd/dbaas_create_pg.go
cmd/dbaas_update_kafka.go
cmd/dbaas_update_mysql.go
cmd/dbaas_update_opensearch.go
cmd/dbaas_update_pg.go
go.mod
go.sum
vendor/github.com/exoscale/egoscale/v3/operations.go
vendor/github.com/exoscale/egoscale/v3/schemas.go
vendor/github.com/exoscale/egoscale/v3/version.go
vendor/modules.txt

Merge this one first: https://github.com/exoscale/egoscale/pull/700

Bump egoscale: Fix some DBAAS resources

---

CHANGELOG.md
cmd/compute/deploy_target/deploy_target_list.go
cmd/compute/deploy_target/deploy_target_show.go

```
➜  ~/exo/cli git:(tgrondier/feat/deploy-target-egoscale-v3) ✗ go run . compute deploy-target list                                                                                                                                                                                                           25-06-17 10:16 
┼──────────┼──────────────────────────────────────┼────────────────────┼───────────┼
│   ZONE   │                  ID                  │        NAME        │   TYPE    │
┼──────────┼──────────────────────────────────────┼────────────────────┼───────────┼
│ ch-gva-2 │ .................................... │ xxxxxxxxxxxxxxxxxx │ dedicated │
...
➜  ~/exo/cli git:(tgrondier/feat/deploy-target-egoscale-v3) ✗ go run . compute deploy-target show …
```

deploy target: move to egoscale v3

---

install-latest.sh

make sure it's sh compatible using shellcheck
Tried with POSIX sh
```
ubuntu@test:~$ curl -fsSL https://raw.githubusercontent.com/exoscale/cli/d8edc17b4f15a3161fd4bffeff33b81e33b72a9a/install-latest.sh | sh
gpg: directory '/home/ubuntu/.gnupg' created
gpg: keybox '/home/ubuntu/.gnupg/pubring.kbx' created
gpg: /home/ubuntu/.gnupg/trustdb.gpg: trustdb created
gpg: key 03686F8CDE378D41: public key "Exoscale Tooling <tooling@exoscale.ch>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Installing exo CLI, using apt
Hit:1 http://de.archive.ubuntu.com/ubuntu noble InRelease
Get:2 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]
Get:3 http://de.archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Get:4 …
```

Install script: make sure it's POSIX sh compatible

---

CHANGELOG.md
cmd/compute/instance_type/instance_type_list.go
cmd/compute/instance_type/instance_type_show.go

Details in individual commit messages

instance-type: use egoscale v3

---

CHANGELOG.md
cmd/compute/instance_pool/instance_pool_delete.go
cmd/compute/instance_pool/instance_pool_evict.go
cmd/compute/instance_pool/instance_pool_list.go
cmd/compute/instance_pool/instance_pool_scale.go
cmd/compute/instance_pool/instance_pool_show.go
cmd/compute/instance_pool/instance_pool_update.go

Testing in individual commit messages

instancepool: update to egoscale v3
